DROP TABLE `decisions`;--> statement-breakpoint
DROP TABLE `doc_series`;--> statement-breakpoint
DROP TABLE `doc_series_meta`;--> statement-breakpoint
DROP TABLE `effort_year`;--> statement-breakpoint
DROP TABLE `event_observers`;--> statement-breakpoint
DROP TABLE `events`;--> statement-breakpoint
DROP TABLE `ias_species`;--> statement-breakpoint
DROP TABLE `instruments`;--> statement-breakpoint
DROP TABLE `interventions`;--> statement-breakpoint
DROP TABLE `landuse_change`;--> statement-breakpoint
DROP TABLE `landuse_watershed`;--> statement-breakpoint
DROP TABLE `meas_clim`;--> statement-breakpoint
DROP TABLE `meas_daily`;--> statement-breakpoint
DROP TABLE `meas_month`;--> statement-breakpoint
DROP TABLE `meas_year`;--> statement-breakpoint
DROP TABLE `measurements`;--> statement-breakpoint
DROP TABLE `mesh_all`;--> statement-breakpoint
DROP TABLE `mesh_species`;--> statement-breakpoint
DROP TABLE `mesh_year`;--> statement-breakpoint
DROP TABLE `observers`;--> statement-breakpoint
DROP TABLE `org_group_year`;--> statement-breakpoint
DROP TABLE `org_norm`;--> statement-breakpoint
DROP TABLE `org_watershed`;--> statement-breakpoint
DROP TABLE `org_watershed_year`;--> statement-breakpoint
DROP TABLE `organism_records`;--> statement-breakpoint
DROP TABLE `protocols`;--> statement-breakpoint
DROP TABLE `quality_monthly`;--> statement-breakpoint
DROP TABLE `quality_transitions`;--> statement-breakpoint
DROP TABLE `rain_daily`;--> statement-breakpoint
DROP TABLE `redlist_assessments`;--> statement-breakpoint
DROP TABLE `redlist_change`;--> statement-breakpoint
DROP TABLE `redlist_map`;--> statement-breakpoint
DROP TABLE `sensor_daily`;--> statement-breakpoint
DROP TABLE `sensor_hour_month`;--> statement-breakpoint
DROP TABLE `sensor_timeseries`;--> statement-breakpoint
DROP TABLE `site_var`;--> statement-breakpoint
DROP TABLE `species2`;--> statement-breakpoint
DROP TABLE `species_mesh_year`;--> statement-breakpoint
DROP TABLE `species_month`;--> statement-breakpoint
DROP TABLE `species_year2`;--> statement-breakpoint
DROP TABLE `taxa`;--> statement-breakpoint
DROP TABLE `var_catalog`;--> statement-breakpoint
DROP TABLE `watershed_meta`;--> statement-breakpoint
DROP TABLE `watershed_rollup`;--> statement-breakpoint
DROP TABLE `zone_clim`;--> statement-breakpoint
DROP TABLE `zone_year`;