-- table: cells (286 rows, generated by scripts/s01_build_sample.py)
INSERT INTO "cells" ("id", "doc_id", "doc_sha256", "page_no", "table_id", "row_key", "col_key", "value_raw", "value", "value_type", "unit", "fiscal_year", "era_raw", "source_text", "source_bbox", "notes_ref", "is_total", "merged", "unreadable_reason", "confidence", "extractor", "verified_by", "extracted_at", "superseded") VALUES
(24366, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 1, 'p1_t1', '最寄りの警察署（110）', 'TEL', 'TEL', '"TEL"', 'string', NULL, NULL, NULL, 'きましょう）
最寄りの消防署（119） TEL
最寄りの警察署（110） TEL
救急', '[245.3, 653.2, 514.7, 676.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24367, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 1, 'p1_t1', '救急病院', 'TEL', 'TEL', '"TEL"', 'string', NULL, NULL, NULL, 'きましょう）
最寄りの消防署（119） TEL
最寄りの警察署（110） TEL
救急', '[245.3, 676.3, 514.7, 699.2]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24368, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 1, 'p1_t1', 'いであ(株)（事務局）', 'TEL', 'TEL：045-593-7603', '"TEL\uff1a045-593-7603"', 'string', NULL, NULL, NULL, '急病院 TEL
いであ(株)（事務局） TEL：045-593-7603
神奈川県環境科学ｾﾝﾀｰ TEL：04', '[245.3, 699.2, 514.7, 722.2]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24369, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 1, 'p1_t1', '神奈川県環境科学ｾﾝﾀｰ', 'TEL', 'TEL：0463-24-3311', '"TEL\uff1a0463-24-3311"', 'string', NULL, NULL, NULL, '45-593-7603
神奈川県環境科学ｾﾝﾀｰ TEL：0463-24-3311
1', '[245.3, 722.2, 514.7, 744.8]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24370, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 2, 'p2_t1', '【全項目共通】記録用紙、筆記用具、カメラ、調査マニュアル、図鑑（必要に応じて）水質測定機材（棒温度計、デジタル水温計、透視度計、溶存酸素計、ｐＨメーター、ＣＯＤ用パックテスト）', '植物を入れるビニール袋、剪定ばさみ、新聞紙（水草を調査する場合は、胴長、ライフジャケット、ジッパー付きビニール袋）|胴長、ライフジャケット、タモ網、バケツ、白色バット、観察用アクリル水槽、サンプル瓶、固定液（エタノール）|胴長、ライフジャケット、タモ網、バケツ、白色バット、ピンセット、ルーペ、サンプル瓶、固定液（エタノール）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24371, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 5, 'p5_t1', '植物|オオキンケイギク、オオカワヂシャ、アレチウリ、オオフサモ、ボタンウキクサ', '種名', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24372, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 5, 'p5_t1', '植物|オオキンケイギク、オオカワヂシャ、アレチウリ、オオフサモ、ボタンウキクサ', '種名', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24373, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '両生類', '分類', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24374, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '両生類', '分類', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24375, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '両生類', '分類|放置|殺処分（放置）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[287.9, 253.7, 337.5, 308.2]', NULL, 0, 1, 'cell_text_not_found_in_page_rawtext: ''殺処分（放置）''', NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24376, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '両生類', '対処法|放置|殺処分（放置）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24377, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '両生類', '対処法|放置|殺処分（放置）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24378, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '両生類', '対処法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[337.5, 253.7, 546.7, 308.2]', NULL, 0, 1, 'cell_text_not_found_in_page_rawtext: ''殺す（心情的に殺処分できないときは、必ず採取された場所に戻す）''', NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24379, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '両生類', '具体的な方法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24380, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '両生類', '具体的な方法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24381, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|植物', '分類', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24382, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|植物', '分類', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24383, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|植物', '分類|放置|殺処分（放置）', '処分', '"\u51e6\u5206"', 'string', '種', NULL, NULL, 'れてしまったら？
以下の表を参考にして、処分をしてください。重要なことは、「生息範囲', '[287.9, 308.2, 337.5, 344.8]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24384, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|植物', '対処法|放置|殺処分（放置）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24385, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|植物', '対処法|放置|殺処分（放置）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24386, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|植物', '対処法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[337.5, 308.2, 546.7, 344.8]', NULL, 0, 1, 'cell_text_not_found_in_page_rawtext: ''種等が飛ばないよう、袋に入れて封をして、燃えるゴミとして出す''', NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24387, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|植物', '具体的な方法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24388, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|植物', '具体的な方法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24389, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|魚類足の生えていないオタマジャクシを含む', '分類', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24390, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|魚類足の生えていないオタマジャクシを含む', '分類', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24391, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|魚類足の生えていないオタマジャクシを含む', '分類|放置|殺処分（放置）', '殺処分', '"\u6bba\u51e6\u5206"', 'string', '種', NULL, NULL, '体的な方法
調査で採れて、 植物 放置 殺処分できる状況ではないほど茂ってい
その場で', '[287.9, 344.8, 337.5, 399.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24392, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|魚類足の生えていないオタマジャクシを含む', '対処法|放置|殺処分（放置）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24393, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|魚類足の生えていないオタマジャクシを含む', '対処法|放置|殺処分（放置）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24394, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|魚類足の生えていないオタマジャクシを含む', '対処法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[337.5, 344.8, 546.7, 399.2]', NULL, 0, 1, 'cell_text_not_found_in_page_rawtext: ''・そのまま土に埋める・冷凍して殺してから燃えるゴミとして出す''', NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24395, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|魚類足の生えていないオタマジャクシを含む', '具体的な方法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24396, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|魚類足の生えていないオタマジャクシを含む', '具体的な方法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24397, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|両生類', '分類', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24398, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|両生類', '分類', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24399, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|両生類', '分類|放置|殺処分（放置）', '殺処分', '"\u6bba\u51e6\u5206"', 'string', '種', NULL, NULL, '体的な方法
調査で採れて、 植物 放置 殺処分できる状況ではないほど茂ってい
その場で', '[287.9, 399.2, 337.5, 417.8]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24400, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|両生類', '対処法|放置|殺処分（放置）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24401, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|両生類', '対処法|放置|殺処分（放置）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24402, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|両生類', '対処法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', '冷凍してから燃えるゴミとして出す', '"\u51b7\u51cd\u3057\u3066\u304b\u3089\u71c3\u3048\u308b\u30b4\u30df\u3068\u3057\u3066\u51fa\u3059"', 'string', '種', NULL, NULL, 'タマジャクシを含む す
両生類 殺処分 冷凍してから燃えるゴミとして出す
参考：環境省ホームページ 外来生物法 ', '[337.5, 399.2, 546.7, 417.8]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24403, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|両生類', '具体的な方法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24404, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 6, 'p6_t1', '調査で採れた生き物で、持ち帰って同定した結果、特定外来種とわかった場合（魚類・両生類で標本になっているものは除く）|両生類', '具体的な方法|殺処分できる状況ではないほど茂っていることが多いので、そのまま放置する|採れた川の河原や川縁に埋める（心情的に殺処分できないときは、必ず採取された場所に戻す）', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:58', 0),
(24405, 'kanagawa_river_monitoring_anzen', 'b4d4970298099682f2ff67552f0cb727cda1e18dadcb85ba3abc3380609faed2', 7, 'p7_t2', NULL, '(cid:158)VUTS(cid:220)(cid:129)x‰ UTŁÆ.(cid:224)(cid:128)(cid:17)(cid:217)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[405.4, 688.2, 422.7, 745.5]', NULL, 0, 0, 'cell_text_not_found_in_page_rawtext: ''(cid:138)4|‘V(cid:143)(cid:27)(cid:17)(cid:217) #ª(cid:140)(cid:129)(cid:226)?4(cid:138)2''', NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:18:59', 0),
(25180, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 2, 'p2_t1', NULL, NULL, 'クロモ、葉は5～７枚', '"\u30af\u30ed\u30e2\u3001\u8449\u306f5\uff5e\uff17\u679a"', 'string', NULL, NULL, NULL, 'コカナダモ
やクロモより大き
いです。
クロモ、葉は5～７枚
葉は３枚ずつ出ることが多く、オオカナダ', '[202.1, 259.6, 285.3, 271.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25181, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 2, 'p2_t1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[202.1, 271.4, 285.3, 309.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25182, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 2, 'p2_t5', '葉の縁はノコギリ状で、波打つのが特徴です。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25183, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 2, 'p2_t6', NULL, NULL, '葉柄', '"\u8449\u67c4"', 'string', NULL, NULL, NULL, '） □ ササバモ（在来種）
葉には、長い葉柄(ようへ
い)があるのが特徴です。
葉柄', '[446.6, 376.6, 540.2, 506.8]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25184, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 3, 'p3_t2', '大きな白い穂が目立ちます。茎本ずつ出るのが特徴で、ススキす。やや湿った場所に多くみら', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[485.3, 278.7, 539.7, 313.2]', NULL, 0, 0, 'cell_text_not_found_in_page_rawtext: ''は地面から１と区別されまれます。''', NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25185, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 3, 'p3_t3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[254.8, 396.8, 286.0, 514.1]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25186, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 3, 'p3_t4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25187, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 3, 'p3_t4', 'ツルヨシの"つる"', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25188, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 3, 'p3_t4', 'ツルヨシの"つる"', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25189, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 3, 'p3_t4', 'ツルヨシの"つる"', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[500.5, 461.9, 539.7, 514.1]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25190, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 3, 'p3_t6', NULL, NULL, '花に長い芒(のぎ)があります。', '"\u82b1\u306b\u9577\u3044\u8292(\u306e\u304e)\u304c\u3042\u308a\u307e\u3059\u3002"', 'string', NULL, NULL, NULL, 'かいのが特徴です。 は、草丈が2m程になります。
花に長い芒(のぎ)
があります。
写真提供：相模原市立博物館', '[461.1, 687.6, 539.7, 716.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25191, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 4, 'p4_t1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[192.9, 198.9, 285.5, 309.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25192, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 4, 'p4_t2', NULL, '葉脈が多いのが特徴です(片側20本以上)。大きいものは、高さ1.5m程になります。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[334.5, 170.7, 341.9, 179.7]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25193, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 4, 'p4_t2', NULL, '葉脈が多いのが特徴です(片側20本以上)。大きいものは、高さ1.5m程になります。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[334.5, 179.7, 341.9, 185.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25194, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 4, 'p4_t5', '渓谷の湿った岩場に生えます。葉は細長く、小さいです(長さ2cm程', '度)。', '度)。', '"\u5ea6)\u3002"', 'string', 'm', NULL, NULL, 'に のも特徴
葉は細長く、小さいです(長さ2cm程度)。 生えます。 です。', '[209.8, 675.4, 224.0, 704.7]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25195, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 4, 'p4_t6', NULL, 'です。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[444.5, 592.7, 540.3, 704.7]', NULL, 0, 0, 'cell_text_not_found_in_page_rawtext: ''が赤いも特徴す。''', NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25196, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 4, 'p4_t6', '茎ので', 'です。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[444.5, 660.6, 473.4, 704.7]', NULL, 0, 0, 'cell_text_not_found_in_page_rawtext: ''が赤いも特徴す。''', NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25197, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 4, 'p4_t6', '水辺の泥地などに生えます。|茎ので', 'です。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25198, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 5, 'p5_t1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[197.9, 252.8, 285.9, 312.9]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25199, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 5, 'p5_t1', '礫河原に生えます。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25200, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 5, 'p5_t2', '芽生えの葉は、白っぽく見えます', '河原の砂～礫地に生えます。葉は細長く、糸状です。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25201, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 5, 'p5_t5', '食用にするセリです。春の七草のひとつです。', NULL, '食用にするセリです。春の七草のひとつです。', '"\u98df\u7528\u306b\u3059\u308b\u30bb\u30ea\u3067\u3059\u3002\u6625\u306e\u4e03\u8349\u306e\u3072\u3068\u3064\u3067\u3059\u3002"', 'string', NULL, NULL, NULL, ' そのほかに見つけた植物を記録しよう！
食用にするセリです。
春の七草のひとつです。
写真提供：相模原市立博物館、線画：「神', '[172.5, 554.7, 285.9, 586.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25202, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 6, 'p6_t1', '葉に特徴があります。奇数羽状複葉といいます。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25203, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 6, 'p6_t1', '葉に特徴があります。奇数羽状複葉といいます。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25204, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 6, 'p6_t1', '枝などにトゲがあります。砂防や養蜂用等に植えられた歴史があります。|葉に特徴があります。奇数羽状複葉といいます。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25205, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 6, 'p6_t2', '茎や葉が、地面から束になって出て、こんもりとした印象になります。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25206, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 6, 'p6_t3', NULL, NULL, '実実ににもも毛毛ががあありり、、', '"\u5b9f\u5b9f\u306b\u306b\u3082\u3082\u6bdb\u6bdb\u304c\u304c\u3042\u3042\u308a\u308a\u3001\u3001"', 'string', NULL, NULL, NULL, '～７角形で、手の平よりやや大きいです。
実実ににもも毛毛ががあありり、、
硬く鋭い。危険!!
葉のオほオとフんサ', '[209.0, 412.9, 284.8, 423.1]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25207, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 6, 'p6_t3', NULL, NULL, '硬く鋭い。危険!!', '"\u786c\u304f\u92ed\u3044\u3002\u5371\u967a!!"', 'string', NULL, NULL, NULL, 'す。
実実ににもも毛毛ががあありり、、
硬く鋭い。危険!!
葉のオほオとフんサどモが(特水定上外に', '[209.0, 423.1, 284.8, 443.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25208, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 6, 'p6_t3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(25209, 'kanagawa_river_monitoring_syokubutu', 'fc4db7f8acd5eefb29aa58795aec3c333d113e6e0df1a0e368bd7064ce9ae746', 6, 'p6_t4', '葉のオほオとフんサどモが(特水定上外に来出生物ま)す。枝分かれをたくさんして増殖します。群生地をつくり、生態系を乱す存在です。特定外来生物に指定されます。', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:19:06', 0),
(69495, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t1', 'ボランティア登録数', '令和4年度', '129', '129', 'int', NULL, 2022, '令和4年度', '令和元年度 平成30年度
ボランティア
129 132 146 191 228
登録数', '[153.5, 410.9, 229.7, 447.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69496, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t1', 'ボランティア登録数', '令和3年度', '132', '132', 'int', NULL, 2021, '令和3年度', '度 平成30年度
ボランティア
129 132 146 191 228
登録数
*ボラ', '[229.7, 410.9, 303.3, 447.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69497, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t1', 'ボランティア登録数', '令和2年度', '146', '146', 'int', NULL, 2020, '令和2年度', '30年度
ボランティア
129 132 146 191 228
登録数
*ボランティア', '[303.3, 410.9, 375.6, 447.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69498, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t1', 'ボランティア登録数', '令和元年度', '191', '191', 'int', NULL, 2019, '令和元年度', '
ボランティア
129 132 146 191 228
登録数
*ボランティア登録数は', '[375.6, 410.9, 450.0, 447.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69499, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t1', 'ボランティア登録数', '平成30年度', '228', '228', 'int', NULL, 2018, '平成30年度', 'ティア
129 132 146 191 228
登録数
*ボランティア登録数は、各年度', '[450.0, 410.9, 524.3, 447.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69500, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t2', '活動延べ人数', '令和4年度', '340', '340', 'int', NULL, 2022, '令和4年度', '一般ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[148.7, 537.8, 223.3, 556.1]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69501, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t2', '活動延べ人数', '令和3年度', '633', '633', 'int', NULL, 2021, '令和3年度', '度 平成30年度
活動延べ人数 340 633 690 1,083 1,185
(3)', '[223.3, 537.8, 299.1, 556.1]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69502, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t2', '活動延べ人数', '令和2年度', '690', '690', 'int', NULL, 2020, '令和2年度', '30年度
活動延べ人数 340 633 690 1,083 1,185
(3) ボラン', '[299.1, 537.8, 375.6, 556.1]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69503, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t2', '活動延べ人数', '令和元年度', '1,083', '1083', 'int', NULL, 2019, '令和元年度', '
活動延べ人数 340 633 690 1,083 1,185
(3) ボランティアへの飼', '[375.6, 537.8, 450.0, 556.1]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69504, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t2', '活動延べ人数', '平成30年度', '1,185', '1185', 'int', NULL, 2018, '平成30年度', '数 340 633 690 1,083 1,185
(3) ボランティアへの飼養依頼
（件', '[450.0, 537.8, 524.3, 556.1]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69505, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '鳥 類|短 期', '令和4年度', '0', '0', 'int', NULL, 2022, '令和4年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[153.5, 640.1, 223.3, 661.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69506, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '鳥 類|短 期', '令和3年度', '1', '1', 'int', NULL, 2021, '令和3年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[223.3, 640.1, 293.4, 661.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69507, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '鳥 類|短 期', '令和2年度', '0', '0', 'int', NULL, 2020, '令和2年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[293.4, 640.1, 363.7, 661.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69508, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '鳥 類|短 期', '令和元年度', '1', '1', 'int', NULL, 2019, '令和元年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[363.7, 640.1, 434.0, 661.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69509, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '鳥 類|短 期', '平成30年度', '1', '1', 'int', NULL, 2018, '平成30年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[434.0, 640.1, 504.3, 661.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69510, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '鳥 類|長 期', '令和4年度', '0', '0', 'int', NULL, 2022, '令和4年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[153.5, 661.3, 223.3, 682.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69511, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '鳥 類|長 期', '令和3年度', '0', '0', 'int', NULL, 2021, '令和3年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[223.3, 661.3, 293.4, 682.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69512, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '鳥 類|長 期', '令和2年度', '3', '3', 'int', NULL, 2020, '令和2年度', '3 ボランティアの活動
・当センターには野生動物の飼', '[293.4, 661.3, 363.7, 682.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69513, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '鳥 類|長 期', '令和元年度', '1', '1', 'int', NULL, 2019, '令和元年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[363.7, 661.3, 434.0, 682.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69514, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '鳥 類|長 期', '平成30年度', '3', '3', 'int', NULL, 2018, '平成30年度', '3 ボランティアの活動
・当センターには野生動物の飼', '[434.0, 661.3, 504.3, 682.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69515, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '哺乳類|短 期', '令和4年度', '0', '0', 'int', NULL, 2022, '令和4年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[153.5, 682.4, 223.3, 704.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69516, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '哺乳類|短 期', '令和3年度', '0', '0', 'int', NULL, 2021, '令和3年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[223.3, 682.4, 293.4, 704.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69517, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '哺乳類|短 期', '令和2年度', '0', '0', 'int', NULL, 2020, '令和2年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[293.4, 682.4, 363.7, 704.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69518, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '哺乳類|短 期', '令和元年度', '0', '0', 'int', NULL, 2019, '令和元年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[363.7, 682.4, 434.0, 704.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69519, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '哺乳類|短 期', '平成30年度', '0', '0', 'int', NULL, 2018, '平成30年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[434.0, 682.4, 504.3, 704.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69520, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '哺乳類|長 期', '令和4年度', '0', '0', 'int', NULL, 2022, '令和4年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[153.5, 704.0, 223.3, 725.0]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69521, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '哺乳類|長 期', '令和3年度', '0', '0', 'int', NULL, 2021, '令和3年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[223.3, 704.0, 293.4, 725.0]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69522, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '哺乳類|長 期', '令和2年度', '0', '0', 'int', NULL, 2020, '令和2年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[293.4, 704.0, 363.7, 725.0]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69523, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '哺乳類|長 期', '令和元年度', '0', '0', 'int', NULL, 2019, '令和元年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[363.7, 704.0, 434.0, 725.0]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69524, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '哺乳類|長 期', '平成30年度', '0', '0', 'int', NULL, 2018, '平成30年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[434.0, 704.0, 504.3, 725.0]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69525, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '合 計|短 期', '令和4年度', '0', '0', 'int', NULL, 2022, '令和4年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[153.5, 725.0, 223.3, 746.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69526, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '合 計|短 期', '令和3年度', '1', '1', 'int', NULL, 2021, '令和3年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[223.3, 725.0, 293.4, 746.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69527, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '合 計|短 期', '令和2年度', '0', '0', 'int', NULL, 2020, '令和2年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[293.4, 725.0, 363.7, 746.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69528, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '合 計|短 期', '令和元年度', '1', '1', 'int', NULL, 2019, '令和元年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[363.7, 725.0, 434.0, 746.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69529, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '合 計|短 期', '平成30年度', '1', '1', 'int', NULL, 2018, '平成30年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[434.0, 725.0, 504.3, 746.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69530, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '合 計|長 期', '令和4年度', '0', '0', 'int', NULL, 2022, '令和4年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[153.5, 746.6, 223.3, 767.6]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69531, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '合 計|長 期', '令和3年度', '0', '0', 'int', NULL, 2021, '令和3年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[223.3, 746.6, 293.4, 767.6]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69532, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '合 計|長 期', '令和2年度', '3', '3', 'int', NULL, 2020, '令和2年度', '3 ボランティアの活動
・当センターには野生動物の飼', '[293.4, 746.6, 363.7, 767.6]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69533, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '合 計|長 期', '令和元年度', '1', '1', 'int', NULL, 2019, '令和元年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[363.7, 746.6, 434.0, 767.6]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69534, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '合 計|長 期', '平成30年度', '3', '3', 'int', NULL, 2018, '平成30年度', '3 ボランティアの活動
・当センターには野生動物の飼', '[434.0, 746.6, 504.3, 767.6]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69535, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '総 計|長 期', '令和4年度', '0', '0', 'int', NULL, 2022, '令和4年度', 'ボランティアの活動人
数は年間延べ 340 人で、毎年多くの方々にご参加いただいて', '[153.5, 767.6, 223.3, 788.7]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69536, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '総 計|長 期', '令和3年度', '1', '1', 'int', NULL, 2021, '令和3年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[223.3, 767.6, 293.4, 788.7]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69537, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '総 計|長 期', '令和2年度', '3', '3', 'int', NULL, 2020, '令和2年度', '3 ボランティアの活動
・当センターには野生動物の飼', '[293.4, 767.6, 363.7, 788.7]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69538, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '総 計|長 期', '令和元年度', '2', '2', 'int', NULL, 2019, '令和元年度', 'ア（注 1）、短期飼養ボランティア（注 2）
および長期飼養ボランティア（注3）が', '[363.7, 767.6, 434.0, 788.7]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69539, 'choju_kyugo_jisseki_2022', '399f794175360a87c6cea6653c51f607ce4c66bb7a705ed8435c2e623007bedd', 4, 'p4_t3', '総 計|長 期', '平成30年度', '4', '4', 'int', NULL, 2018, '平成30年度', '飼養ボランティア（注3）があります。令和4年度の一般ボランティアの活動人
数は年間', '[434.0, 767.6, 504.3, 788.7]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:36', 0),
(69804, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t1', '鳥 類', '種 類', '50', '50', 'int', '種', NULL, NULL, ' 種 類 頭、羽 割 合（％）
鳥 類 50 280 85.4
哺乳類 5 44 1', '[100.5, 232.6, 155.1, 245.8]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69805, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t1', '鳥 類', '頭、羽', '280', '280', 'int', '頭', NULL, NULL, '類 頭、羽 割 合（％）
鳥 類 50 280 85.4
哺乳類 5 44 14.6
', '[155.1, 232.6, 239.1, 245.8]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69806, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t1', '鳥 類', '割 合（％）', '85.4', '85.4', 'float', '％', NULL, NULL, '羽 割 合（％）
鳥 類 50 280 85.4
哺乳類 5 44 14.6
合 計 5', '[239.1, 232.6, 335.7, 245.8]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69807, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t1', '哺乳類', '種 類', '5', '5', 'int', '種', NULL, NULL, ' 種 類 頭、羽 割 合（％）
鳥 類 50 280 85.4
哺乳類 5 44 ', '[100.5, 245.8, 155.1, 258.9]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69808, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t1', '哺乳類', '頭、羽', '44', '44', 'int', '頭', NULL, NULL, '類 50 280 85.4
哺乳類 5 44 14.6
合 計 55 324 100', '[155.1, 245.8, 239.1, 258.9]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69809, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t1', '哺乳類', '割 合（％）', '14.6', '14.6', 'float', '％', NULL, NULL, '0 280 85.4
哺乳類 5 44 14.6
合 計 55 324 100
参考（過', '[239.1, 245.8, 335.7, 258.9]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69810, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t1', '合 計', '種 類', '55', '55', 'int', '種', NULL, NULL, '4
哺乳類 5 44 14.6
合 計 55 324 100
参考（過去5ヵ年の救護', '[100.5, 258.9, 155.1, 272.1]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69811, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t1', '合 計', '頭、羽', '324', '324', 'int', '頭', NULL, NULL, '乳類 5 44 14.6
合 計 55 324 100
参考（過去5ヵ年の救護状況）
', '[155.1, 258.9, 239.1, 272.1]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69812, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t1', '合 計', '割 合（％）', '100', '100', 'int', '％', NULL, NULL, ' 44 14.6
合 計 55 324 100
参考（過去5ヵ年の救護状況）
(1) ', '[239.1, 258.9, 335.7, 272.1]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69813, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '鳥 類', '令和2年度', '280', '280', 'int', NULL, 2020, '令和2年度', '類 頭、羽 割 合（％）
鳥 類 50 280 85.4
哺乳類 5 44 14.6
', '[108.3, 349.2, 144.9, 364.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69814, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '鳥 類', '令和2年度', '(22)', '22', 'int', NULL, 2020, '令和2年度', '29年度 平成28年度
鳥 類 280 (22) 275 (23) 284 (23) 4', '[144.9, 349.2, 181.5, 364.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69815, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '鳥 類', '令和元年度', '275', '275', 'int', NULL, 2019, '令和元年度', '平成28年度
鳥 類 280 (22) 275 (23) 284 (23) 445 (', '[181.5, 349.2, 218.1, 364.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69816, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '鳥 類', '令和元年度', '(23)', '23', 'int', NULL, 2019, '令和元年度', '年度
鳥 類 280 (22) 275 (23) 284 (23) 445 (15) 4', '[218.1, 349.2, 254.7, 364.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69817, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '鳥 類', '平成30年度', '284', '284', 'int', NULL, 2018, '平成30年度', '類 280 (22) 275 (23) 284 (23) 445 (15) 436 (', '[254.7, 349.2, 291.3, 364.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69818, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '鳥 類', '平成30年度', '(23)', '23', 'int', NULL, 2018, '平成30年度', '年度
鳥 類 280 (22) 275 (23) 284 (23) 445 (15) 4', '[291.3, 349.2, 327.8, 364.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69819, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '鳥 類', '平成29年度', '445', '445', 'int', NULL, 2017, '平成29年度', ') 275 (23) 284 (23) 445 (15) 436 (35)
哺乳類 4', '[327.8, 349.2, 364.4, 364.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69820, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '鳥 類', '平成29年度', '(15)', '15', 'int', NULL, 2017, '平成29年度', '5 (23) 284 (23) 445 (15) 436 (35)
哺乳類 44 (3)', '[364.4, 349.2, 401.0, 364.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69821, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '鳥 類', '平成28年度', '436', '436', 'int', NULL, 2016, '平成28年度', ') 284 (23) 445 (15) 436 (35)
哺乳類 44 (3) 47 ', '[401.0, 349.2, 437.6, 364.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69822, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '鳥 類', '平成28年度', '(35)', '35', 'int', NULL, 2016, '平成28年度', '4 (23) 445 (15) 436 (35)
哺乳類 44 (3) 47 (2) 4', '[437.6, 349.2, 474.2, 364.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69823, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '哺乳類', '令和2年度', '44', '44', 'int', NULL, 2020, '令和2年度', '類 50 280 85.4
哺乳類 5 44 14.6
合 計 55 324 100', '[108.3, 364.3, 144.9, 377.5]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69824, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '哺乳類', '令和2年度', '(3)', '3', 'int', NULL, 2020, '令和2年度', '15) 436 (35)
哺乳類 44 (3) 47 (2) 40 (2) 53 (3', '[144.9, 364.3, 181.5, 377.5]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69825, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '哺乳類', '令和元年度', '47', '47', 'int', NULL, 2019, '令和元年度', '436 (35)
哺乳類 44 (3) 47 (2) 40 (2) 53 (3) 5', '[181.5, 364.3, 218.1, 377.5]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69826, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '哺乳類', '令和元年度', '(2)', '2', 'int', NULL, 2019, '令和元年度', ' (35)
哺乳類 44 (3) 47 (2) 40 (2) 53 (3) 53 (5', '[218.1, 364.3, 254.7, 377.5]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69827, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '哺乳類', '平成30年度', '40', '40', 'int', NULL, 2018, '平成30年度', ')
哺乳類 44 (3) 47 (2) 40 (2) 53 (3) 53 (5)
計', '[254.7, 364.3, 291.3, 377.5]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69828, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '哺乳類', '平成30年度', '(2)', '2', 'int', NULL, 2018, '平成30年度', ' (35)
哺乳類 44 (3) 47 (2) 40 (2) 53 (3) 53 (5', '[291.3, 364.3, 327.8, 377.5]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69829, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '哺乳類', '平成29年度', '53', '53', 'int', NULL, 2017, '平成29年度', '4 (3) 47 (2) 40 (2) 53 (3) 53 (5)
計 324 (2', '[327.8, 364.3, 364.4, 377.5]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69830, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '哺乳類', '平成29年度', '(3)', '3', 'int', NULL, 2017, '平成29年度', '15) 436 (35)
哺乳類 44 (3) 47 (2) 40 (2) 53 (3', '[364.4, 364.3, 401.0, 377.5]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69831, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '哺乳類', '平成28年度', '53', '53', 'int', NULL, 2016, '平成28年度', '4 (3) 47 (2) 40 (2) 53 (3) 53 (5)
計 324 (2', '[401.0, 364.3, 437.6, 377.5]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69832, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '哺乳類', '平成28年度', '(5)', '5', 'int', NULL, 2016, '平成28年度', '2) 40 (2) 53 (3) 53 (5)
計 324 (25) 322 (25)', '[437.6, 364.3, 474.2, 377.5]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69833, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '計', '令和2年度', '324', '324', 'int', NULL, 2020, '令和2年度', '乳類 5 44 14.6
合 計 55 324 100
参考（過去5ヵ年の救護状況）
', '[108.3, 377.5, 144.9, 390.7]', NULL, 1, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69834, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '計', '令和2年度', '(25)', '25', 'int', NULL, 2020, '令和2年度', '53 (3) 53 (5)
計 324 (25) 322 (25) 324 (25) 4', '[144.9, 377.5, 181.5, 390.7]', NULL, 1, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69835, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '計', '令和元年度', '322', '322', 'int', NULL, 2019, '令和元年度', ') 53 (5)
計 324 (25) 322 (25) 324 (25) 498 (', '[181.5, 377.5, 218.1, 390.7]', NULL, 1, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69836, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '計', '令和元年度', '(25)', '25', 'int', NULL, 2019, '令和元年度', '53 (3) 53 (5)
計 324 (25) 322 (25) 324 (25) 4', '[218.1, 377.5, 254.7, 390.7]', NULL, 1, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69837, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '計', '平成30年度', '324', '324', 'int', NULL, 2018, '平成30年度', '乳類 5 44 14.6
合 計 55 324 100
参考（過去5ヵ年の救護状況）
', '[254.7, 377.5, 291.3, 390.7]', NULL, 1, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69838, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '計', '平成30年度', '(25)', '25', 'int', NULL, 2018, '平成30年度', '53 (3) 53 (5)
計 324 (25) 322 (25) 324 (25) 4', '[291.3, 377.5, 327.8, 390.7]', NULL, 1, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69839, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '計', '平成29年度', '498', '498', 'int', NULL, 2017, '平成29年度', ') 322 (25) 324 (25) 498 (18) 489 (40)
*（）はへ', '[327.8, 377.5, 364.4, 390.7]', NULL, 1, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69840, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '計', '平成29年度', '(18)', '18', 'int', NULL, 2017, '平成29年度', '2 (25) 324 (25) 498 (18) 489 (40)
*（）はへい死体で持', '[364.4, 377.5, 401.0, 390.7]', NULL, 1, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69841, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '計', '平成28年度', '489', '489', 'int', NULL, 2016, '平成28年度', ') 324 (25) 498 (18) 489 (40)
*（）はへい死体で持ち込まれ', '[401.0, 377.5, 437.6, 390.7]', NULL, 1, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69842, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 1, 'p1_t2', '計', '平成28年度', '(40)', '40', 'int', NULL, 2016, '平成28年度', '4 (25) 498 (18) 489 (40)
*（）はへい死体で持ち込まれたもので、', '[437.6, 377.5, 474.2, 390.7]', NULL, 1, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:37', 0),
(69843, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '令和2年度', '放野', '"\u653e\u91ce"', 'string', NULL, 2020, '令和2年度', '16
アオバト 7 メジロ 9
(4) 放野率・死亡率（％）
令和2年度 令和元年度', '[86.8, 289.4, 118.2, 300.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69844, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '令和2年度', '死亡', '"\u6b7b\u4ea1"', 'string', NULL, 2020, '令和2年度', 'オバト 7 メジロ 9
(4) 放野率・死亡率（％）
令和2年度 令和元年度 平成3', '[118.2, 289.4, 150.1, 300.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69845, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '令和2年度', 'その他', '"\u305d\u306e\u4ed6"', 'string', NULL, 2020, '令和2年度', '平成29年度 平成28年度
放野 死亡 その他 放野 死亡 その他 放野 死亡 その他', '[150.1, 289.4, 182.1, 300.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69846, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '令和元年度', '放野', '"\u653e\u91ce"', 'string', NULL, 2019, '令和元年度', '16
アオバト 7 メジロ 9
(4) 放野率・死亡率（％）
令和2年度 令和元年度', '[182.1, 289.4, 214.1, 300.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69847, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '令和元年度', '死亡', '"\u6b7b\u4ea1"', 'string', NULL, 2019, '令和元年度', 'オバト 7 メジロ 9
(4) 放野率・死亡率（％）
令和2年度 令和元年度 平成3', '[214.1, 289.4, 246.0, 300.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69848, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '令和元年度', 'その他', '"\u305d\u306e\u4ed6"', 'string', NULL, 2019, '令和元年度', '平成29年度 平成28年度
放野 死亡 その他 放野 死亡 その他 放野 死亡 その他', '[246.0, 289.4, 278.0, 300.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69849, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '平成30年度', '放野', '"\u653e\u91ce"', 'string', NULL, 2018, '平成30年度', '16
アオバト 7 メジロ 9
(4) 放野率・死亡率（％）
令和2年度 令和元年度', '[278.0, 289.4, 307.2, 300.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69850, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '平成30年度', '死亡', '"\u6b7b\u4ea1"', 'string', NULL, 2018, '平成30年度', 'オバト 7 メジロ 9
(4) 放野率・死亡率（％）
令和2年度 令和元年度 平成3', '[307.2, 289.4, 336.6, 300.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69851, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '平成30年度', 'その他', '"\u305d\u306e\u4ed6"', 'string', NULL, 2018, '平成30年度', '平成29年度 平成28年度
放野 死亡 その他 放野 死亡 その他 放野 死亡 その他', '[336.6, 289.4, 365.7, 300.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69852, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '平成29年度', '放野', '"\u653e\u91ce"', 'string', NULL, 2017, '平成29年度', '16
アオバト 7 メジロ 9
(4) 放野率・死亡率（％）
令和2年度 令和元年度', '[365.7, 289.4, 394.9, 300.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69853, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '平成29年度', '死亡', '"\u6b7b\u4ea1"', 'string', NULL, 2017, '平成29年度', 'オバト 7 メジロ 9
(4) 放野率・死亡率（％）
令和2年度 令和元年度 平成3', '[394.9, 289.4, 425.8, 300.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69854, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '平成29年度', 'その他', '"\u305d\u306e\u4ed6"', 'string', NULL, 2017, '平成29年度', '平成29年度 平成28年度
放野 死亡 その他 放野 死亡 その他 放野 死亡 その他', '[425.8, 289.4, 451.8, 300.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69855, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '平成28年度', '放野', '"\u653e\u91ce"', 'string', NULL, 2016, '平成28年度', '16
アオバト 7 メジロ 9
(4) 放野率・死亡率（％）
令和2年度 令和元年度', '[451.8, 289.4, 482.6, 300.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69856, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '平成28年度', '死亡', '"\u6b7b\u4ea1"', 'string', NULL, 2016, '平成28年度', 'オバト 7 メジロ 9
(4) 放野率・死亡率（％）
令和2年度 令和元年度 平成3', '[482.6, 289.4, 511.8, 300.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69857, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', NULL, '平成28年度', 'その他', '"\u305d\u306e\u4ed6"', 'string', NULL, 2016, '平成28年度', '平成29年度 平成28年度
放野 死亡 その他 放野 死亡 その他 放野 死亡 その他', '[511.8, 289.4, 541.1, 300.4]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69858, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '令和2年度', '41.1', '41.1', 'float', NULL, 2020, '令和2年度', '亡 その他 放野 死亡 その他
鳥 類 41.1 45.7 13.2 54.4 40.1', '[86.8, 300.4, 118.2, 311.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69859, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '令和2年度', '45.7', '45.7', 'float', NULL, 2020, '令和2年度', ' 放野 死亡 その他
鳥 類 41.1 45.7 13.2 54.4 40.1 5.6 ', '[118.2, 300.4, 150.1, 311.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69860, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '令和2年度', '13.2', '13.2', 'float', NULL, 2020, '令和2年度', '亡 その他
鳥 類 41.1 45.7 13.2 54.4 40.1 5.6 44.4 ', '[150.1, 300.4, 182.1, 311.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69861, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '令和元年度', '54.4', '54.4', 'float', NULL, 2019, '令和元年度', '
鳥 類 41.1 45.7 13.2 54.4 40.1 5.6 44.4 46.8 ', '[182.1, 300.4, 214.1, 311.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69862, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '令和元年度', '40.1', '40.1', 'float', NULL, 2019, '令和元年度', '41.1 45.7 13.2 54.4 40.1 5.6 44.4 46.8 8.8 2', '[214.1, 300.4, 246.0, 311.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69863, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '令和元年度', '5.6', '5.6', 'float', NULL, 2019, '令和元年度', '45.7 13.2 54.4 40.1 5.6 44.4 46.8 8.8 29.5 ', '[246.0, 300.4, 278.0, 311.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69864, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '平成30年度', '44.4', '44.4', 'float', NULL, 2018, '平成30年度', ' 13.2 54.4 40.1 5.6 44.4 46.8 8.8 29.5 61.9 ', '[278.0, 300.4, 307.2, 311.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69865, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '平成30年度', '46.8', '46.8', 'float', NULL, 2018, '平成30年度', ' 54.4 40.1 5.6 44.4 46.8 8.8 29.5 61.9 8.6 3', '[307.2, 300.4, 336.6, 311.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69866, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '平成30年度', '8.8', '8.8', 'float', NULL, 2018, '平成30年度', ' 40.1 5.6 44.4 46.8 8.8 29.5 61.9 8.6 37.7 ', '[336.6, 300.4, 365.7, 311.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69867, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '平成29年度', '29.5', '29.5', 'float', NULL, 2017, '平成29年度', '1 5.6 44.4 46.8 8.8 29.5 61.9 8.6 37.7 54.1 ', '[365.7, 300.4, 394.9, 311.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69868, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '平成29年度', '61.9', '61.9', 'float', NULL, 2017, '平成29年度', ' 44.4 46.8 8.8 29.5 61.9 8.6 37.7 54.1 8.2
哺', '[394.9, 300.4, 425.8, 311.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69869, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '平成29年度', '8.6', '8.6', 'float', NULL, 2017, '平成29年度', ' 46.8 8.8 29.5 61.9 8.6 37.7 54.1 8.2
哺乳類 4', '[425.8, 300.4, 451.8, 311.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69870, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '平成28年度', '37.7', '37.7', 'float', NULL, 2016, '平成28年度', '8 8.8 29.5 61.9 8.6 37.7 54.1 8.2
哺乳類 47.4 5', '[451.8, 300.4, 482.6, 311.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69871, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '平成28年度', '54.1', '54.1', 'float', NULL, 2016, '平成28年度', ' 29.5 61.9 8.6 37.7 54.1 8.2
哺乳類 47.4 50.0 2', '[482.6, 300.4, 511.8, 311.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69872, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '鳥 類', '平成28年度', '8.2', '8.2', 'float', NULL, 2016, '平成28年度', ' 61.9 8.6 37.7 54.1 8.2
哺乳類 47.4 50.0 2.6 2', '[511.8, 300.4, 541.1, 311.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69873, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '令和2年度', '47.4', '47.4', 'float', NULL, 2020, '令和2年度', '6 37.7 54.1 8.2
哺乳類 47.4 50.0 2.6 24.4 53.3 ', '[86.8, 311.3, 118.2, 322.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69874, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '令和2年度', '50.0', '50.0', 'float', NULL, 2020, '令和2年度', '7 54.1 8.2
哺乳類 47.4 50.0 2.6 24.4 53.3 22.2 ', '[118.2, 311.3, 150.1, 322.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69875, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '令和2年度', '2.6', '2.6', 'float', NULL, 2020, '令和2年度', '1 8.2
哺乳類 47.4 50.0 2.6 24.4 53.3 22.2 39.5', '[150.1, 311.3, 182.1, 322.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69876, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '令和元年度', '24.4', '24.4', 'float', NULL, 2019, '令和元年度', '2
哺乳類 47.4 50.0 2.6 24.4 53.3 22.2 39.5 13.2', '[182.1, 311.3, 214.1, 322.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69877, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '令和元年度', '53.3', '53.3', 'float', NULL, 2019, '令和元年度', ' 47.4 50.0 2.6 24.4 53.3 22.2 39.5 13.2 47.4', '[214.1, 311.3, 246.0, 322.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69878, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '令和元年度', '22.2', '22.2', 'float', NULL, 2019, '令和元年度', ' 50.0 2.6 24.4 53.3 22.2 39.5 13.2 47.4 36.0', '[246.0, 311.3, 278.0, 322.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69879, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '平成30年度', '39.5', '39.5', 'float', NULL, 2018, '平成30年度', ' 2.6 24.4 53.3 22.2 39.5 13.2 47.4 36.0 42.0', '[278.0, 311.3, 307.2, 322.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69880, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '平成30年度', '13.2', '13.2', 'float', NULL, 2018, '平成30年度', '亡 その他
鳥 類 41.1 45.7 13.2 54.4 40.1 5.6 44.4 ', '[307.2, 311.3, 336.6, 322.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69881, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '平成30年度', '47.4', '47.4', 'float', NULL, 2018, '平成30年度', '6 37.7 54.1 8.2
哺乳類 47.4 50.0 2.6 24.4 53.3 ', '[336.6, 311.3, 365.7, 322.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69882, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '平成29年度', '36.0', '36.0', 'float', NULL, 2017, '平成29年度', '22.2 39.5 13.2 47.4 36.0 42.0 22.0 34.1 47.7', '[365.7, 311.3, 394.9, 322.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69883, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '平成29年度', '42.0', '42.0', 'float', NULL, 2017, '平成29年度', '39.5 13.2 47.4 36.0 42.0 22.0 34.1 47.7 18.2', '[394.9, 311.3, 425.8, 322.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69884, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '平成29年度', '22.0', '22.0', 'float', NULL, 2017, '平成29年度', '13.2 47.4 36.0 42.0 22.0 34.1 47.7 18.2
全 体 ', '[425.8, 311.3, 451.8, 322.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69885, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '平成28年度', '34.1', '34.1', 'float', NULL, 2016, '平成28年度', '47.4 36.0 42.0 22.0 34.1 47.7 18.2
全 体 41.9 ', '[451.8, 311.3, 482.6, 322.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69886, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '平成28年度', '47.7', '47.7', 'float', NULL, 2016, '平成28年度', '36.0 42.0 22.0 34.1 47.7 18.2
全 体 41.9 46.3 ', '[482.6, 311.3, 511.8, 322.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69887, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '哺乳類', '平成28年度', '18.2', '18.2', 'float', NULL, 2016, '平成28年度', '42.0 22.0 34.1 47.7 18.2
全 体 41.9 46.3 11.8 ', '[511.8, 311.3, 541.1, 322.3]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69888, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '令和2年度', '41.9', '41.9', 'float', NULL, 2020, '令和2年度', ' 34.1 47.7 18.2
全 体 41.9 46.3 11.8 49.8 42.1', '[86.8, 322.3, 118.2, 333.2]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0);
INSERT INTO "cells" ("id", "doc_id", "doc_sha256", "page_no", "table_id", "row_key", "col_key", "value_raw", "value", "value_type", "unit", "fiscal_year", "era_raw", "source_text", "source_bbox", "notes_ref", "is_total", "merged", "unreadable_reason", "confidence", "extractor", "verified_by", "extracted_at", "superseded") VALUES
(69889, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '令和2年度', '46.3', '46.3', 'float', NULL, 2020, '令和2年度', ' 47.7 18.2
全 体 41.9 46.3 11.8 49.8 42.1 8.1 ', '[118.2, 322.3, 150.1, 333.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69890, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '令和2年度', '11.8', '11.8', 'float', NULL, 2020, '令和2年度', ' 18.2
全 体 41.9 46.3 11.8 49.8 42.1 8.1 42.1 ', '[150.1, 322.3, 182.1, 333.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69891, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '令和元年度', '49.8', '49.8', 'float', NULL, 2019, '令和元年度', '
全 体 41.9 46.3 11.8 49.8 42.1 8.1 42.1 45.5 ', '[182.1, 322.3, 214.1, 333.2]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69892, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '令和元年度', '42.1', '42.1', 'float', NULL, 2019, '令和元年度', '41.9 46.3 11.8 49.8 42.1 8.1 42.1 45.5 12.4 ', '[214.1, 322.3, 246.0, 333.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69893, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '令和元年度', '8.1', '8.1', 'float', NULL, 2019, '令和元年度', '46.3 11.8 49.8 42.1 8.1 42.1 45.5 12.4 30.2', '[246.0, 322.3, 278.0, 333.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69894, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '平成30年度', '42.1', '42.1', 'float', NULL, 2018, '平成30年度', '41.9 46.3 11.8 49.8 42.1 8.1 42.1 45.5 12.4 ', '[278.0, 322.3, 307.2, 333.2]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69895, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '平成30年度', '45.5', '45.5', 'float', NULL, 2018, '平成30年度', ' 49.8 42.1 8.1 42.1 45.5 12.4 30.2 59.8 10.0', '[307.2, 322.3, 336.6, 333.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69896, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '平成30年度', '12.4', '12.4', 'float', NULL, 2018, '平成30年度', ' 42.1 8.1 42.1 45.5 12.4 30.2 59.8 10.0 36.7', '[336.6, 322.3, 365.7, 333.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69897, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '平成29年度', '30.2', '30.2', 'float', NULL, 2017, '平成29年度', ' 8.1 42.1 45.5 12.4 30.2 59.8 10.0 36.7 53.2', '[365.7, 322.3, 394.9, 333.2]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69898, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '平成29年度', '59.8', '59.8', 'float', NULL, 2017, '平成29年度', '42.1 45.5 12.4 30.2 59.8 10.0 36.7 53.2 10.0', '[394.9, 322.3, 425.8, 333.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69899, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '平成29年度', '10.0', '10.0', 'float', NULL, 2017, '平成29年度', '45.5 12.4 30.2 59.8 10.0 36.7 53.2 10.0
*各年度', '[425.8, 322.3, 451.8, 333.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69900, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '平成28年度', '36.7', '36.7', 'float', NULL, 2016, '平成28年度', '12.4 30.2 59.8 10.0 36.7 53.2 10.0
*各年度の3月31', '[451.8, 322.3, 482.6, 333.2]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69901, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '平成28年度', '53.2', '53.2', 'float', NULL, 2016, '平成28年度', '30.2 59.8 10.0 36.7 53.2 10.0
*各年度の3月31日時点（へ', '[482.6, 322.3, 511.8, 333.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69902, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 2, 'p2_t1', '全 体', '平成28年度', '10.0', '10.0', 'float', NULL, 2016, '平成28年度', '45.5 12.4 30.2 59.8 10.0 36.7 53.2 10.0
*各年度', '[511.8, 322.3, 541.1, 333.2]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69903, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t1', 'ボランティア登録数', '令和2年度', '146', '146', 'int', NULL, 2020, '令和2年度', '成29年度 平成28年度
ボランティア
146 191 228 254 259
登録数', '[156.1, 411.8, 229.7, 448.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69904, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t1', 'ボランティア登録数', '令和元年度', '191', '191', 'int', NULL, 2019, '令和元年度', '度 平成28年度
ボランティア
146 191 228 254 259
登録数
*ボラ', '[229.7, 411.8, 303.3, 448.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69905, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t1', 'ボランティア登録数', '平成30年度', '228', '228', 'int', NULL, 2018, '平成30年度', '28年度
ボランティア
146 191 228 254 259
登録数
*ボランティア', '[303.3, 411.8, 377.2, 448.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69906, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t1', 'ボランティア登録数', '平成29年度', '254', '254', 'int', NULL, 2017, '平成29年度', '
ボランティア
146 191 228 254 259
登録数
*ボランティア登録数は', '[377.2, 411.8, 448.9, 448.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69907, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t1', 'ボランティア登録数', '平成28年度', '259', '259', 'int', NULL, 2016, '平成28年度', 'ティア
146 191 228 254 259
登録数
*ボランティア登録数は、各年度', '[448.9, 411.8, 524.4, 448.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69908, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t2', '活動延べ人数', '令和2年度', '690', '690', 'int', NULL, 2020, '令和2年度', '一般ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[148.7, 538.5, 223.9, 557.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69909, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t2', '活動延べ人数', '令和元年度', '1,083', '1083', 'int', NULL, 2019, '令和元年度', '度 平成28年度
活動延べ人数 690 1,083 1,185 1，217 1,132
(', '[223.9, 538.5, 299.1, 557.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69910, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t2', '活動延べ人数', '平成30年度', '1,185', '1185', 'int', NULL, 2018, '平成30年度', '年度
活動延べ人数 690 1,083 1,185 1，217 1,132
(3) ボラン', '[299.1, 538.5, 377.2, 557.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69911, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t2', '活動延べ人数', '平成29年度', '1，217', '1217', 'int', NULL, 2017, '平成29年度', 'べ人数 690 1,083 1,185 1，217 1,132
(3) ボランティアへの飼', '[377.2, 538.5, 448.9, 557.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69912, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t2', '活動延べ人数', '平成28年度', '1,132', '1132', 'int', NULL, 2016, '平成28年度', '0 1,083 1,185 1，217 1,132
(3) ボランティアへの飼養依頼
（件', '[448.9, 538.5, 524.4, 557.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69913, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '鳥 類|短 期', '令和2年度', '0', '0', 'int', NULL, 2020, '令和2年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[166.9, 641.0, 237.3, 662.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69914, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '鳥 類|短 期', '令和元年度', '1', '1', 'int', NULL, 2019, '令和元年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[237.3, 641.0, 307.6, 662.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69915, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '鳥 類|短 期', '平成30年度', '1', '1', 'int', NULL, 2018, '平成30年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[307.6, 641.0, 377.2, 662.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69916, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '鳥 類|短 期', '平成29年度', '0', '0', 'int', NULL, 2017, '平成29年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[377.2, 641.0, 448.9, 662.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69917, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '鳥 類|短 期', '平成28年度', '0', '0', 'int', NULL, 2016, '平成28年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[448.9, 641.0, 518.6, 662.0]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69918, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '鳥 類|長 期', '令和2年度', '3', '3', 'int', NULL, 2020, '令和2年度', '3 ボランティアの活動
・当センターには野生動物の飼', '[166.9, 662.0, 237.3, 683.1]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69919, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '鳥 類|長 期', '令和元年度', '1', '1', 'int', NULL, 2019, '令和元年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[237.3, 662.0, 307.6, 683.1]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69920, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '鳥 類|長 期', '平成30年度', '3', '3', 'int', NULL, 2018, '平成30年度', '3 ボランティアの活動
・当センターには野生動物の飼', '[307.6, 662.0, 377.2, 683.1]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69921, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '鳥 類|長 期', '平成29年度', '5', '5', 'int', NULL, 2017, '平成29年度', '
注2 短期飼養ボランティア
主に、毎年5月から8月くらいまでの間、シジュウカラ、', '[377.2, 662.0, 448.9, 683.1]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69922, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '鳥 類|長 期', '平成28年度', '0', '0', 'int', NULL, 2016, '平成28年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[448.9, 662.0, 518.6, 683.1]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69923, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '哺乳類|短 期', '令和2年度', '0', '0', 'int', NULL, 2020, '令和2年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[166.9, 683.1, 237.3, 704.7]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69924, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '哺乳類|短 期', '令和元年度', '0', '0', 'int', NULL, 2019, '令和元年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[237.3, 683.1, 307.6, 704.7]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69925, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '哺乳類|短 期', '平成30年度', '0', '0', 'int', NULL, 2018, '平成30年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[307.6, 683.1, 377.2, 704.7]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69926, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '哺乳類|短 期', '平成29年度', '0', '0', 'int', NULL, 2017, '平成29年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[377.2, 683.1, 448.9, 704.7]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69927, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '哺乳類|短 期', '平成28年度', '1', '1', 'int', NULL, 2016, '平成28年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[448.9, 683.1, 518.6, 704.7]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69928, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '哺乳類|長 期', '令和2年度', '0', '0', 'int', NULL, 2020, '令和2年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[166.9, 704.7, 237.3, 725.9]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69929, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '哺乳類|長 期', '令和元年度', '0', '0', 'int', NULL, 2019, '令和元年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[237.3, 704.7, 307.6, 725.9]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69930, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '哺乳類|長 期', '平成30年度', '0', '0', 'int', NULL, 2018, '平成30年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[307.6, 704.7, 377.2, 725.9]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69931, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '哺乳類|長 期', '平成29年度', '0', '0', 'int', NULL, 2017, '平成29年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[377.2, 704.7, 448.9, 725.9]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69932, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '哺乳類|長 期', '平成28年度', '1', '1', 'int', NULL, 2016, '平成28年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[448.9, 704.7, 518.6, 725.9]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69933, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '合 計|短 期', '令和2年度', '0', '0', 'int', NULL, 2020, '令和2年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[166.9, 725.9, 237.3, 747.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69934, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '合 計|短 期', '令和元年度', '1', '1', 'int', NULL, 2019, '令和元年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[237.3, 725.9, 307.6, 747.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69935, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '合 計|短 期', '平成30年度', '1', '1', 'int', NULL, 2018, '平成30年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[307.6, 725.9, 377.2, 747.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69936, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '合 計|短 期', '平成29年度', '0', '0', 'int', NULL, 2017, '平成29年度', 'ボランティアの活動人
数は年間延べ 690 人で、毎年多くの方々にご参加いただいて', '[377.2, 725.9, 448.9, 747.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69937, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '合 計|短 期', '平成28年度', '1', '1', 'int', NULL, 2016, '平成28年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[448.9, 725.9, 518.6, 747.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69938, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '合 計|長 期', '令和2年度', '3', '3', 'int', NULL, 2020, '令和2年度', '3 ボランティアの活動
・当センターには野生動物の飼', '[166.9, 747.3, 237.3, 768.5]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69939, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '合 計|長 期', '令和元年度', '1', '1', 'int', NULL, 2019, '令和元年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[237.3, 747.3, 307.6, 768.5]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69940, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '合 計|長 期', '平成30年度', '3', '3', 'int', NULL, 2018, '平成30年度', '3 ボランティアの活動
・当センターには野生動物の飼', '[307.6, 747.3, 377.2, 768.5]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69941, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '合 計|長 期', '平成29年度', '5', '5', 'int', NULL, 2017, '平成29年度', '
注2 短期飼養ボランティア
主に、毎年5月から8月くらいまでの間、シジュウカラ、', '[377.2, 747.3, 448.9, 768.5]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69942, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '合 計|長 期', '平成28年度', '1', '1', 'int', NULL, 2016, '平成28年度', '護ボランティアには一般ボランティア（注 1）、短期飼養ボランティア（注 2）
およ', '[448.9, 747.3, 518.6, 768.5]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69943, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '総 計|長 期', '令和2年度', '3', '3', 'int', NULL, 2020, '令和2年度', '3 ボランティアの活動
・当センターには野生動物の飼', '[166.9, 768.5, 237.3, 789.6]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69944, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '総 計|長 期', '令和元年度', '2', '2', 'int', NULL, 2019, '令和元年度', 'ア（注 1）、短期飼養ボランティア（注 2）
および長期飼養ボランティア（注3）が', '[237.3, 768.5, 307.6, 789.6]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69945, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '総 計|長 期', '平成30年度', '4', '4', 'int', NULL, 2018, '平成30年度', '29年度 平成28年度
ボランティア
146 191 228 254 259
登録', '[307.6, 768.5, 377.2, 789.6]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69946, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '総 計|長 期', '平成29年度', '5', '5', 'int', NULL, 2017, '平成29年度', '
注2 短期飼養ボランティア
主に、毎年5月から8月くらいまでの間、シジュウカラ、', '[377.2, 768.5, 448.9, 789.6]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(69947, 'choju_kyugo_jisseki_2020', 'f58c135724f66df13b86ec93bb855e602529b74eaaa0f7b7b7085490659bcc19', 4, 'p4_t3', '総 計|長 期', '平成28年度', '2', '2', 'int', NULL, 2016, '平成28年度', 'ア（注 1）、短期飼養ボランティア（注 2）
および長期飼養ボランティア（注3）が', '[448.9, 768.5, 518.6, 789.6]', NULL, 0, 1, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:38', 0),
(74802, 'choju_kyugo_jisseki_2012', 'dfe936db4ba33b3f7d4f175dc7680fc3eedb1c6877bcc8f016302369c30d0165', 1, 'p1_t2', NULL, NULL, '65 66', '6566', 'int', NULL, NULL, NULL, '24
24 591 23 633
24
65 66 496 542 83.9 (85.6 ', '[149.9, 318.1, 236.3, 332.9]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74803, 'choju_kyugo_jisseki_2012', 'dfe936db4ba33b3f7d4f175dc7680fc3eedb1c6877bcc8f016302369c30d0165', 1, 'p1_t2', NULL, NULL, '496 542', '496542', 'int', NULL, NULL, NULL, '591 23 633
24
65 66 496 542 83.9 (85.6 )
12 10 ', '[236.3, 318.1, 322.7, 332.9]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74804, 'choju_kyugo_jisseki_2012', 'dfe936db4ba33b3f7d4f175dc7680fc3eedb1c6877bcc8f016302369c30d0165', 1, 'p1_t2', NULL, NULL, '83.9 (85.6 )', '"83.9 (85.6 )"', 'string', NULL, NULL, NULL, '33
24
65 66 496 542 83.9 (85.6 )
12 10 95 91 16.1 (1', '[322.7, 318.1, 430.7, 332.9]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74805, 'choju_kyugo_jisseki_2012', 'dfe936db4ba33b3f7d4f175dc7680fc3eedb1c6877bcc8f016302369c30d0165', 1, 'p1_t2', NULL, NULL, '12 10', '1210', 'int', NULL, NULL, NULL, '96 542 83.9 (85.6 )
12 10 95 91 16.1 (14.4 )
', '[149.9, 332.9, 236.3, 347.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74806, 'choju_kyugo_jisseki_2012', 'dfe936db4ba33b3f7d4f175dc7680fc3eedb1c6877bcc8f016302369c30d0165', 1, 'p1_t2', NULL, NULL, '95 91', '9591', 'int', NULL, NULL, NULL, ' 83.9 (85.6 )
12 10 95 91 16.1 (14.4 )
77 76 ', '[236.3, 332.9, 322.7, 347.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74807, 'choju_kyugo_jisseki_2012', 'dfe936db4ba33b3f7d4f175dc7680fc3eedb1c6877bcc8f016302369c30d0165', 1, 'p1_t2', NULL, NULL, '16.1 (14.4 )', '"16.1 (14.4 )"', 'string', NULL, NULL, NULL, '(85.6 )
12 10 95 91 16.1 (14.4 )
77 76 591 633 100 (', '[322.7, 332.9, 430.7, 347.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74808, 'choju_kyugo_jisseki_2012', 'dfe936db4ba33b3f7d4f175dc7680fc3eedb1c6877bcc8f016302369c30d0165', 1, 'p1_t2', NULL, NULL, '77 76', '7776', 'int', NULL, NULL, NULL, ' 95 91 16.1 (14.4 )
77 76 591 633 100 (100 )
', '[149.9, 347.6, 236.3, 362.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74809, 'choju_kyugo_jisseki_2012', 'dfe936db4ba33b3f7d4f175dc7680fc3eedb1c6877bcc8f016302369c30d0165', 1, 'p1_t2', NULL, NULL, '591 633', '591633', 'int', NULL, NULL, NULL, ' 16.1 (14.4 )
77 76 591 633 100 (100 )
23
23
24', '[236.3, 347.6, 322.7, 362.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74810, 'choju_kyugo_jisseki_2012', 'dfe936db4ba33b3f7d4f175dc7680fc3eedb1c6877bcc8f016302369c30d0165', 1, 'p1_t2', NULL, NULL, '100 (100 )', '100100', 'int', NULL, NULL, NULL, '4.4 )
77 76 591 633 100 (100 )
23
23
24 6
24
28
23', '[322.7, 347.6, 430.7, 362.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74811, 'choju_kyugo_jisseki_2011', '7e9c3cc3b63f15fe1b651345447ae72b11c70a40f055816539747c33edcb2a1f', 1, 'p1_t2', NULL, NULL, '66 68', '6668', 'int', NULL, NULL, NULL, '23
23 633 22 604
23
66 68 542 509 85.6 (84.3 ', '[149.9, 318.1, 236.3, 332.9]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74812, 'choju_kyugo_jisseki_2011', '7e9c3cc3b63f15fe1b651345447ae72b11c70a40f055816539747c33edcb2a1f', 1, 'p1_t2', NULL, NULL, '542 509', '542509', 'int', NULL, NULL, NULL, '633 22 604
23
66 68 542 509 85.6 (84.3 )
10 12 ', '[236.3, 318.1, 322.7, 332.9]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74813, 'choju_kyugo_jisseki_2011', '7e9c3cc3b63f15fe1b651345447ae72b11c70a40f055816539747c33edcb2a1f', 1, 'p1_t2', NULL, NULL, '85.6 (84.3 )', '"85.6 (84.3 )"', 'string', NULL, NULL, NULL, '04
23
66 68 542 509 85.6 (84.3 )
10 12 91 95 14.4 (1', '[322.7, 318.1, 430.7, 332.9]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74814, 'choju_kyugo_jisseki_2011', '7e9c3cc3b63f15fe1b651345447ae72b11c70a40f055816539747c33edcb2a1f', 1, 'p1_t2', NULL, NULL, '10 12', '1012', 'int', NULL, NULL, NULL, '42 509 85.6 (84.3 )
10 12 91 95 14.4 (15.7 )
', '[149.9, 332.9, 236.3, 347.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74815, 'choju_kyugo_jisseki_2011', '7e9c3cc3b63f15fe1b651345447ae72b11c70a40f055816539747c33edcb2a1f', 1, 'p1_t2', NULL, NULL, '91 95', '9195', 'int', NULL, NULL, NULL, ' 85.6 (84.3 )
10 12 91 95 14.4 (15.7 )
76 80 ', '[236.3, 332.9, 322.7, 347.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74816, 'choju_kyugo_jisseki_2011', '7e9c3cc3b63f15fe1b651345447ae72b11c70a40f055816539747c33edcb2a1f', 1, 'p1_t2', NULL, NULL, '14.4 (15.7 )', '"14.4 (15.7 )"', 'string', NULL, NULL, NULL, '(84.3 )
10 12 91 95 14.4 (15.7 )
76 80 633 604 100% ', '[322.7, 332.9, 430.7, 347.6]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74817, 'choju_kyugo_jisseki_2011', '7e9c3cc3b63f15fe1b651345447ae72b11c70a40f055816539747c33edcb2a1f', 1, 'p1_t2', NULL, NULL, '76 80', '7680', 'int', NULL, NULL, NULL, ' 91 95 14.4 (15.7 )
76 80 633 604 100% (100%)', '[149.9, 347.6, 236.3, 362.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74818, 'choju_kyugo_jisseki_2011', '7e9c3cc3b63f15fe1b651345447ae72b11c70a40f055816539747c33edcb2a1f', 1, 'p1_t2', NULL, NULL, '633 604', '633604', 'int', NULL, NULL, NULL, ' 14.4 (15.7 )
76 80 633 604 100% (100%)
22
23
2', '[236.3, 347.6, 322.7, 362.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74819, 'choju_kyugo_jisseki_2011', '7e9c3cc3b63f15fe1b651345447ae72b11c70a40f055816539747c33edcb2a1f', 1, 'p1_t2', NULL, NULL, '100% (100%)', '"100% (100%)"', 'string', NULL, NULL, NULL, '5.7 )
76 80 633 604 100% (100%)
22
23
23 11 11
12 2', '[322.7, 347.6, 430.7, 362.4]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:58', 0),
(74820, 'choju_kyugo_jisseki_2010', '2159092d7d9d86bc071162cfa5bba7c3d8c03d855ba0aedd9578a82e1b2759d6', 1, 'p1_t2', NULL, NULL, '68 60', '6860', 'int', NULL, NULL, NULL, '22
22 604 21 612
22
68 60 509 504 84.3 (82.4 ', '[149.9, 316.2, 236.3, 332.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:59', 0),
(74821, 'choju_kyugo_jisseki_2010', '2159092d7d9d86bc071162cfa5bba7c3d8c03d855ba0aedd9578a82e1b2759d6', 1, 'p1_t2', NULL, NULL, '509 504', '509504', 'int', NULL, NULL, NULL, '604 21 612
22
68 60 509 504 84.3 (82.4 )
12 12 ', '[236.3, 316.2, 322.7, 332.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:59', 0),
(74822, 'choju_kyugo_jisseki_2010', '2159092d7d9d86bc071162cfa5bba7c3d8c03d855ba0aedd9578a82e1b2759d6', 1, 'p1_t2', NULL, NULL, '84.3 (82.4 )', '"84.3 (82.4 )"', 'string', NULL, NULL, NULL, '12
22
68 60 509 504 84.3 (82.4 )
12 12 95 108 15.7 (', '[322.7, 316.2, 430.7, 332.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:59', 0),
(74823, 'choju_kyugo_jisseki_2010', '2159092d7d9d86bc071162cfa5bba7c3d8c03d855ba0aedd9578a82e1b2759d6', 1, 'p1_t2', NULL, NULL, '12 12', '1212', 'int', NULL, NULL, NULL, '09 504 84.3 (82.4 )
12 12 95 108 15.7 (17.6 )', '[149.9, 332.3, 236.3, 348.2]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:59', 0),
(74824, 'choju_kyugo_jisseki_2010', '2159092d7d9d86bc071162cfa5bba7c3d8c03d855ba0aedd9578a82e1b2759d6', 1, 'p1_t2', NULL, NULL, '95 108', '95108', 'int', NULL, NULL, NULL, ' 84.3 (82.4 )
12 12 95 108 15.7 (17.6 )
80 72 ', '[236.3, 332.3, 322.7, 348.2]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:59', 0),
(74825, 'choju_kyugo_jisseki_2010', '2159092d7d9d86bc071162cfa5bba7c3d8c03d855ba0aedd9578a82e1b2759d6', 1, 'p1_t2', NULL, NULL, '15.7 (17.6 )', '"15.7 (17.6 )"', 'string', NULL, NULL, NULL, '82.4 )
12 12 95 108 15.7 (17.6 )
80 72 604 612 100 (', '[322.7, 332.3, 430.7, 348.2]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:59', 0),
(74826, 'choju_kyugo_jisseki_2010', '2159092d7d9d86bc071162cfa5bba7c3d8c03d855ba0aedd9578a82e1b2759d6', 1, 'p1_t2', NULL, NULL, '80 72', '8072', 'int', NULL, NULL, NULL, '95 108 15.7 (17.6 )
80 72 604 612 100 (100 )
', '[149.9, 348.2, 236.3, 364.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:59', 0),
(74827, 'choju_kyugo_jisseki_2010', '2159092d7d9d86bc071162cfa5bba7c3d8c03d855ba0aedd9578a82e1b2759d6', 1, 'p1_t2', NULL, NULL, '604 612', '604612', 'int', NULL, NULL, NULL, ' 15.7 (17.6 )
80 72 604 612 100 (100 )
21
22
22', '[236.3, 348.2, 322.7, 364.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:59', 0),
(74828, 'choju_kyugo_jisseki_2010', '2159092d7d9d86bc071162cfa5bba7c3d8c03d855ba0aedd9578a82e1b2759d6', 1, 'p1_t2', NULL, NULL, '100 (100 )', '100100', 'int', NULL, NULL, NULL, '7.6 )
80 72 604 612 100 (100 )
21
22
22 9 1 12
23 ', '[322.7, 348.2, 430.7, 364.3]', NULL, 0, 0, NULL, NULL, 'pdfplumber@0.11.10', NULL, '2026-08-29T15:47:59', 0);
