-- generated by scripts/s01_build_sample.py（sqlite_master.sql をそのまま）
CREATE TABLE edna_detections (
  record_key TEXT PRIMARY KEY,          -- = read_id
  taxon_id TEXT NOT NULL, scientific_name TEXT, vernacular_name TEXT, taxon_rank TEXT, red_list_category TEXT,
  observed_on TEXT,                     -- = collected_on
  lat REAL, lon REAL, coordinate_uncertainty_m REAL,
  attributes_json TEXT NOT NULL         -- 設計 §3.3 の attributes。m07 が組む
);
CREATE TABLE external_dataset (
  dataset_key TEXT PRIMARY KEY,          -- '<source_id>:<dataset_id>'（e-Stat は '<source_id>:<statInfId>'）
  source_id TEXT NOT NULL,
  portal TEXT NOT NULL,                  -- ckan / estat
  dataset_id TEXT NOT NULL,              -- CKAN の UUID（e-Stat は statInfId、境界 GIS は dlserveyId）
  name TEXT,                             -- CKAN の URL 用の名前（e-Stat は NULL）
  title TEXT NOT NULL,
  description TEXT,
  description_truncated INTEGER NOT NULL DEFAULT 0,   -- 収穫時に 800 文字で切ってある（長さがちょうど 800）
  organization TEXT,
  license TEXT,                          -- 空は NULL（不明。除外しない）
  license_url TEXT,
  groups TEXT,                           -- '|' 区切り
  tags TEXT,                             -- '|' 区切り
  n_resources INTEGER NOT NULL DEFAULT 0,
  metadata_modified TEXT,                -- 収穫時点の値（最新は api_url の package_show）
  page_url TEXT NOT NULL,
  api_url TEXT,                          -- CKAN: package_show（UUID 指定）。e-Stat は NULL
  fetched_at TEXT NOT NULL               -- source_registry.fetched_at（出典単位の収穫日）
, n_with_header INTEGER NOT NULL DEFAULT 0);
CREATE TABLE external_resource (
  resource_key TEXT PRIMARY KEY,         -- '<source_id>:<resource_id>'
  dataset_key TEXT NOT NULL,
  name TEXT,
  format TEXT,                           -- 大文字。'SHP,CSV' のようにカンマ区切りが混ざる
  size INTEGER,
  last_modified TEXT,                    -- 収穫時点の値
  direct_url TEXT,                       -- 直リンク（url が空の行は NULL）
  page_url TEXT,
  sheets_json TEXT                       -- NULL か [{sheet, n_rows, n_cols, header: [...] | null, header_basis?}]
);
CREATE TABLE external_resource_format (
  dataset_key TEXT NOT NULL,
  format_norm TEXT NOT NULL,
  resource_key TEXT NOT NULL,
  PRIMARY KEY (dataset_key, format_norm, resource_key)
);
CREATE TABLE mammal_mesh (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mesh_code TEXT, species TEXT, species_ja TEXT,
  survey_label TEXT,              -- 元の列名
  survey_year INTEGER,            -- 西暦。年を持たない調査は NULL
  confirmed INTEGER,              -- 0/1
  lat REAL, lon REAL,             -- メッシュ中心
  source_id TEXT, source_ref TEXT
);
CREATE TABLE measurements (
  measurement_id TEXT PRIMARY KEY, event_id TEXT, site_id TEXT,
  measured_on TEXT, variable TEXT, variable_en TEXT,
  value REAL, value_raw TEXT, unit TEXT, method TEXT,
  instrument_id TEXT, detection_flag TEXT,
  quality_stage TEXT DEFAULT '暫定',        -- 暫定/検証済/公開済
  verified_by TEXT, verified_on TEXT,
  source_id TEXT, source_ref TEXT, is_synthetic INTEGER DEFAULT 0
);
CREATE TABLE organism_records (
  record_id TEXT PRIMARY KEY, event_id TEXT, site_id TEXT,
  observed_on TEXT, scientific_name TEXT, vernacular_name TEXT,
  taxon_rank TEXT, kingdom TEXT, phylum TEXT, class TEXT, "order" TEXT,
  family TEXT, genus TEXT, taxon_key TEXT,
  individual_count REAL, density REAL, density_unit TEXT,
  basis_of_record TEXT, identified_by TEXT, identification_basis TEXT,
  identification_confidence REAL,
  lat REAL, lon REAL, coordinate_uncertainty_m REAL,
  red_list_category TEXT, is_alien INTEGER DEFAULT 0,
  quality_stage TEXT DEFAULT '暫定', publication_scope TEXT DEFAULT '限定共有',
  source_id TEXT, source_ref TEXT, is_synthetic INTEGER DEFAULT 0
, record_license TEXT, license_class TEXT, commercial_ok INTEGER, occurrence_status TEXT);
CREATE TABLE protected_areas (
  area_id TEXT PRIMARY KEY,
  name_ja TEXT,
  category_ja TEXT,               -- 原文の区分名
  category_code TEXT,             -- 我々が付けた英字スラグ
  municipality_ja TEXT,
  area_ha REAL, area_ha_raw TEXT,
  designated_on TEXT, designated_on_raw TEXT,
  lat REAL, lon REAL,
  watershed TEXT, zone INTEGER,   -- m05 が点内判定で埋める(座標があるもののみ)
  note_ja TEXT,
  source_id TEXT, source_ref TEXT
);
CREATE TABLE protocols (
  protocol_id TEXT PRIMARY KEY, name TEXT, version TEXT, domain TEXT,
  steps_json TEXT, source_id TEXT, url TEXT
);
CREATE TABLE quality_transitions (
  id INTEGER PRIMARY KEY AUTOINCREMENT, target_table TEXT, target_id TEXT,
  from_stage TEXT, to_stage TEXT, actor TEXT, occurred_at TEXT, note TEXT
);
CREATE TABLE redlist_assessments (
  assessment_id        TEXT PRIMARY KEY,
  list_name            TEXT NOT NULL,   -- 版の名称
  list_year            INTEGER NOT NULL,
  taxon_group_ja       TEXT,
  taxon_subgroup_ja    TEXT,
  family_ja            TEXT,
  vernacular_name_ja   TEXT,
  scientific_name      TEXT,            -- 2022年版は原資料に記載なし -> NULL のまま（補完禁止）
  category_code        TEXT,            -- 英字コード(EX/CR/EN/VU/NT/DD等)。2022年版は原資料に無くNULL
  category_ja          TEXT,            -- 原文のカテゴリー名をそのまま
  category_prev_ja     TEXT,            -- その版が併記する「前回」カテゴリー
  national_category_ja TEXT,
  note_ja              TEXT,
  taxon_id             TEXT,            -- taxa への対応。機械結合しないため既定NULL
  source_id            TEXT,
  source_ref           TEXT
);
CREATE TABLE river_segments (
  feature_id TEXT PRIMARY KEY,
  name_ja TEXT, section_type TEXT, prefecture_ja TEXT,
  length_m REAL,                  -- 近似値
  start_lat REAL, start_lon REAL, end_lat REAL, end_lon REAL,
  geometry_geojson TEXT,
  source_id TEXT, source_ref TEXT
);
CREATE TABLE sensor_timeseries (
  id INTEGER PRIMARY KEY AUTOINCREMENT, site_id TEXT, datastream TEXT,
  phenomenon_time TEXT, result REAL, unit TEXT, instrument_id TEXT,
  source_id TEXT, is_synthetic INTEGER DEFAULT 0
);
CREATE TABLE sites (
  site_id TEXT PRIMARY KEY, name TEXT, name_en TEXT,
  watershed TEXT, zone INTEGER,            -- Ridge to Reef 1-5
  lat REAL, lon REAL, elevation_m REAL, geohash TEXT,
  municipality TEXT, muni_code TEXT,
  treatment TEXT,                          -- 対策区 / 対照区 / 参照
  established_on TEXT, operator TEXT,
  source_id TEXT, source_ref TEXT, is_synthetic INTEGER DEFAULT 0
);
CREATE TABLE source_registry (
  source_id TEXT PRIMARY KEY, name TEXT, publisher TEXT, url TEXT,
  category TEXT, access_method TEXT, format TEXT, license TEXT,
  redistributable INTEGER, fetched_at TEXT, record_count INTEGER, notes TEXT
);
CREATE TABLE taxa (
  taxon_id TEXT PRIMARY KEY, scientific_name TEXT, vernacular_name_ja TEXT,
  taxon_group_ja TEXT, kingdom TEXT, phylum TEXT, class TEXT, "order" TEXT,
  family TEXT, genus TEXT, gbif_taxon_key TEXT, gbif_match_type TEXT,
  redlist_kanagawa TEXT, redlist_national TEXT, ias_category TEXT,
  source_id TEXT, source_ref TEXT
);
CREATE TABLE vegetation_polygons (
  feature_id TEXT PRIMARY KEY,
  legend_code TEXT, legend_name_ja TEXT,
  veg_division_ja TEXT,
  naturalness REAL, naturalness_class_ja TEXT,
  survey_year INTEGER, block_ja TEXT,
  area_m2 REAL,                   -- 近似値
  centroid_lat REAL, centroid_lon REAL,
  watershed TEXT,
  geometry_geojson TEXT,          -- simplify 済み
  source_id TEXT, source_ref TEXT
);
CREATE TABLE wildlife_sightings (
  sighting_id TEXT PRIMARY KEY,
  species_ja TEXT,
  fiscal_year INTEGER,
  observed_on TEXT,               -- 年度から西暦を決めて正規化。1-3月は翌年
  observed_on_raw TEXT, observed_time_raw TEXT,
  individual_count REAL, individual_count_raw TEXT,
  situation_ja TEXT,              -- 目撃/痕跡/捕殺 等(原文のまま)
  locality_ja TEXT,
  area_kind_ja TEXT,              -- 人里/山中 等(原文のまま)
  municipality_ja TEXT, lat REAL, lon REAL,
  is_preliminary INTEGER DEFAULT 0,  -- 速報値なら 1
  note_ja TEXT,
  source_id TEXT, source_ref TEXT
);
