-- generated by scripts/s01_build_sample.py（sqlite_master.sql をそのまま）
CREATE TABLE measurements (
  measurement_id TEXT PRIMARY KEY, event_id TEXT, site_id TEXT,
  measured_on TEXT, variable TEXT, variable_en TEXT,
  value REAL, value_raw TEXT, unit TEXT, method TEXT,
  instrument_id TEXT, detection_flag TEXT,
  quality_stage TEXT DEFAULT '暫定',        -- 暫定/検証済/公開済
  verified_by TEXT, verified_on TEXT,
  source_id TEXT, source_ref TEXT, is_synthetic INTEGER DEFAULT 0
);
CREATE TABLE organism_records (
  record_id TEXT PRIMARY KEY, event_id TEXT, site_id TEXT,
  observed_on TEXT, scientific_name TEXT, vernacular_name TEXT,
  taxon_rank TEXT, kingdom TEXT, phylum TEXT, class TEXT, "order" TEXT,
  family TEXT, genus TEXT, taxon_key TEXT,
  individual_count REAL, density REAL, density_unit TEXT,
  basis_of_record TEXT, identified_by TEXT, identification_basis TEXT,
  identification_confidence REAL,
  lat REAL, lon REAL, coordinate_uncertainty_m REAL,
  red_list_category TEXT, is_alien INTEGER DEFAULT 0,
  quality_stage TEXT DEFAULT '暫定', publication_scope TEXT DEFAULT '限定共有',
  source_id TEXT, source_ref TEXT, is_synthetic INTEGER DEFAULT 0
, record_license TEXT, license_class TEXT, commercial_ok INTEGER);
CREATE TABLE quality_transitions (
  id INTEGER PRIMARY KEY AUTOINCREMENT, target_table TEXT, target_id TEXT,
  from_stage TEXT, to_stage TEXT, actor TEXT, occurred_at TEXT, note TEXT
);
CREATE TABLE redlist_assessments (
  assessment_id        TEXT PRIMARY KEY,
  list_name            TEXT NOT NULL,   -- 版の名称
  list_year            INTEGER NOT NULL,
  taxon_group_ja       TEXT,
  taxon_subgroup_ja    TEXT,
  family_ja            TEXT,
  vernacular_name_ja   TEXT,
  scientific_name      TEXT,            -- 2022年版は原資料に記載なし -> NULL のまま（補完禁止）
  category_code        TEXT,            -- 英字コード(EX/CR/EN/VU/NT/DD等)。2022年版は原資料に無くNULL
  category_ja          TEXT,            -- 原文のカテゴリー名をそのまま
  category_prev_ja     TEXT,            -- その版が併記する「前回」カテゴリー
  national_category_ja TEXT,
  note_ja              TEXT,
  taxon_id             TEXT,            -- taxa への対応。機械結合しないため既定NULL
  source_id            TEXT,
  source_ref           TEXT
);
CREATE TABLE sensor_timeseries (
  id INTEGER PRIMARY KEY AUTOINCREMENT, site_id TEXT, datastream TEXT,
  phenomenon_time TEXT, result REAL, unit TEXT, instrument_id TEXT,
  source_id TEXT, is_synthetic INTEGER DEFAULT 0
);
CREATE TABLE sites (
  site_id TEXT PRIMARY KEY, name TEXT, name_en TEXT,
  watershed TEXT, zone INTEGER,            -- Ridge to Reef 1-5
  lat REAL, lon REAL, elevation_m REAL, geohash TEXT,
  municipality TEXT, muni_code TEXT,
  treatment TEXT,                          -- 対策区 / 対照区 / 参照
  established_on TEXT, operator TEXT,
  source_id TEXT, source_ref TEXT, is_synthetic INTEGER DEFAULT 0
);
CREATE TABLE taxa (
  taxon_id TEXT PRIMARY KEY, scientific_name TEXT, vernacular_name_ja TEXT,
  taxon_group_ja TEXT, kingdom TEXT, phylum TEXT, class TEXT, "order" TEXT,
  family TEXT, genus TEXT, gbif_taxon_key TEXT, gbif_match_type TEXT,
  redlist_kanagawa TEXT, redlist_national TEXT, ias_category TEXT,
  source_id TEXT, source_ref TEXT
);
