#!/usr/bin/env python3
"""縮小サンプル（Issue #29「縮小サンプル＋実行証明」A-1）を原本から切り出す。

    .venv/bin/python3 scripts/s01_build_sample.py

読むのは常に読み取り専用（原本 `data/db/ryuiki.sqlite`/`cells.sqlite`・
`data/processed/*`）で、書くのは `data/sample/` 配下のテキストだけ
（sqlite バイナリは一切書かない——コミット対象はテキストにする、という
CLAUDE.md 「サンプル」設計の要件）。

## 何を選ぶか（宣言）と、どう閉包を取るか（コード）

`data/sample/coverage.yaml` の `predicates`（table + where + limit の3つ組。
`ORDER BY rowid LIMIT` で決定論的に選ぶ）と `full_closures`（where に一致する
全行、上限なし）が「何を含めるか」の宣言。このスクリプトは次の閉包を
コード側で追加する:

- **地点×変数の全期間**（`measurements` のみ。`sensor_timeseries` は
  対象外——時系列が密で全期間展開すると閉包が数万行に膨らむため、
  `coverage.yaml` の predicate 自体で `source_id` ごとに小さく上限を切っている）。
- **`quality_transitions`（丸ごと）が参照する `measurements.measurement_id`**。
  `quality_transitions` は「丸ごと入れるもの」だが、参照先の測定行が
  サンプルに無いと「親行が無い」状態になる（閉包「参照の整合」）。
- **属の全記録**は `coverage.yaml` の `full_closures`（`genus = 'Sirosporium'`、
  上限なし）自体がそのまま閉包になっている——追加のコードは無い。
- **文書単位**（`cells.sqlite` の `cells`）は `document_closure.doc_ids` で
  指定した `doc_id` の全セルを入れる。

## 決定論

述語＋`ORDER BY rowid`＋固定の上限で選ぶ（乱数は使わない）。同じ原本から
2回実行するとテキストがバイト単位で一致する（`scripts/tests/
test_s01_build_sample.py::test_determinism`）。挿入順は原本の rowid 順を
保つ——`scripts/s02_materialize_sample.py` が同じ順で `INSERT` するので、
材料化したサンプルの新しい rowid も相対順が保たれる（b06 の
`source_row_id=rowid` やメモ化のタイブレークが依存する性質）。

## 出力

- `data/sample/ryuiki_schema.sql` / `data/sample/cells_schema.sql`:
  対象テーブルの `CREATE TABLE` 文（`sqlite_master.sql` からそのまま）。
- `data/sample/ryuiki/<table>.sql` / `data/sample/cells/<table>.sql`:
  `INSERT INTO ... VALUES (...);` の並び（`rowid` 昇順）。
- `data/sample/processed/<file>`: `wholesale_processed_files` のコピー。
- `data/sample/manifest.json`: 原本・入力ファイルの sha256、テーブルごとの
  サンプル行数。
- `data/sample/declaration_counts.yaml`: 件数の宣言の上書き値
  （`scripts/migrate/period.apply_count_overlay` が読む形。§A-2）。
- `data/sample/derived_keys.yaml`: `reports/derived_baseline.json`
  （原本由来。正）の33表の `key` をそのままサンプル用の宣言的キーにする
  （§A-3。サンプルでは行数が少なく別の列組み合わせでも偶然一意になり
  うるため、全量と同じキーを強制する）。
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import pathlib
import shutil
import sqlite3
import sys
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from migrate import point_in_polygon as pip  # noqa: E402
from reconcile.common import load_yaml  # noqa: E402

DEFAULT_RYUIKI_DB = ROOT / "data" / "db" / "ryuiki.sqlite"
DEFAULT_CELLS_DB = ROOT / "data" / "db" / "cells.sqlite"
DEFAULT_PROCESSED_DIR = ROOT / "data" / "processed"
DEFAULT_COVERAGE_YAML = ROOT / "data" / "sample" / "coverage.yaml"
DEFAULT_BASELINE_JSON = ROOT / "reports" / "derived_baseline.json"
DEFAULT_OUT_DIR = ROOT / "data" / "sample"
DEFAULT_GEOJSON = ROOT / "data" / "processed" / "nlni_w12_watersheds.geojson"

# ---------------------------------------------------------------------------
# 小さなユーティリティ
# ---------------------------------------------------------------------------


def _open_ro(path) -> sqlite3.Connection:
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def _sha256_file(path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _sql_literal(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, (bytes, bytearray)):
        return "X'" + value.hex() + "'"
    return "'" + str(value).replace("'", "''") + "'"


_INSERT_BATCH_SIZE = 200


def _write_table_sql(conn: sqlite3.Connection, table: str, rowids: list[int], out_path: pathlib.Path) -> int:
    """`rowids`（昇順であること）の行を `INSERT INTO table (...) VALUES (...), (...), ...;`
    の複数行 VALUES（`_INSERT_BATCH_SIZE` 行ごと）でまとめて `out_path` に書く。
    列名は `PRAGMA table_info` の現在の並び。

    複数行 VALUES にまとめる理由: `INSERT INTO "table" (col1, ..., colN) VALUES`
    の列名の並びを1行ごとに繰り返すと、テキストの大半が繰り返しの列名になり
    サンプルのテキスト総量（目安10MB前後）を無駄に押し上げる
    （measurements 実測: 1行ごとの INSERT で26MB → バッチ化で大幅に縮小）。
    `sqlite3.Connection.executescript()` は複数行 VALUES を問題なく実行できる。
    """
    columns = [r[1] for r in conn.execute(f'PRAGMA table_info("{table}")')]
    col_list = ", ".join(f'"{c}"' for c in columns)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"-- table: {table} ({len(rowids)} rows, generated by scripts/s01_build_sample.py)"]
    if rowids:
        select_cols = ", ".join(f'"{c}"' for c in columns)
        for i in range(0, len(rowids), _INSERT_BATCH_SIZE):
            batch = rowids[i : i + _INSERT_BATCH_SIZE]
            ph = ",".join("?" * len(batch))
            rows = conn.execute(
                f'SELECT {select_cols} FROM "{table}" WHERE rowid IN ({ph}) ORDER BY rowid', batch
            ).fetchall()
            value_tuples = [
                "(" + ", ".join(_sql_literal(row[c]) for c in columns) + ")" for row in rows
            ]
            lines.append(f'INSERT INTO "{table}" ({col_list}) VALUES\n' + ",\n".join(value_tuples) + ";")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(rowids)


def _write_schema_sql(conn: sqlite3.Connection, tables: list[str], out_path: pathlib.Path) -> None:
    lines = [
        "-- generated by scripts/s01_build_sample.py（sqlite_master.sql をそのまま）",
    ]
    for table in tables:
        row = conn.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)
        ).fetchone()
        if row is None or row["sql"] is None:
            raise SystemExit(f"{table} の CREATE TABLE 文が見つからない")
        lines.append(row["sql"].rstrip().rstrip(";") + ";")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# 選択（predicates + full_closures）
# ---------------------------------------------------------------------------


def _select_rowids(conn: sqlite3.Connection, table: str, where: str, limit: int | None) -> list[int]:
    sql = f'SELECT rowid FROM "{table}" WHERE {where} ORDER BY rowid'
    if limit is not None:
        sql += f" LIMIT {int(limit)}"
    return [r[0] for r in conn.execute(sql)]


def select_ryuiki_rowids(conn: sqlite3.Connection, coverage: dict) -> dict[str, set[int]]:
    """`predicates`/`full_closures` を評価し、テーブル名 -> rowid の集合を返す
    （この時点ではまだ「地点×変数の全期間」等の閉包を含まない）。
    """
    default_limit = coverage.get("default_limit", 20)
    selected: dict[str, set[int]] = defaultdict(set)
    for pred in coverage.get("predicates", []):
        table = pred["table"]
        limit = pred.get("limit", default_limit)
        rowids = _select_rowids(conn, table, pred["where"], limit)
        if not rowids:
            raise SystemExit(f"predicate {pred['name']!r}: 1行も一致しなかった（{table}: {pred['where']}）")
        selected[table].update(rowids)
    for closure in coverage.get("full_closures", []):
        table = closure["table"]
        rowids = _select_rowids(conn, table, closure["where"], None)
        if not rowids:
            raise SystemExit(f"full_closures {closure['name']!r}: 1行も一致しなかった（{table}: {closure['where']}）")
        selected[table].update(rowids)
    return selected


def apply_measurement_site_variable_closure(conn: sqlite3.Connection, rowids: set[int]) -> set[int]:
    """`measurements` の選択済み rowid から `(site_id, variable)` の組を集め、
    それぞれの組の全期間（全 rowid）を閉包に足す。

    `full_closures`（SS閉包25,167行・地盤沈下閉包3,286行）を含む数万件になり
    うるため、SQLite のバインドパラメータ上限を超えないよう大きな `IN (...)`
    は作らずテンポラリテーブルに実体化してから JOIN する。
    """
    if not rowids:
        return set(rowids)
    _create_rowid_temp_table(conn, "__s01_closure_seed", rowids)
    pairs = conn.execute(
        "SELECT DISTINCT m.site_id, m.variable FROM measurements m "
        "JOIN temp.__s01_closure_seed s ON m.rowid = s.rowid_value"
    ).fetchall()
    closed = set(rowids)
    for row in pairs:
        more = conn.execute(
            "SELECT rowid FROM measurements WHERE site_id IS ? AND variable IS ?",
            (row["site_id"], row["variable"]),
        ).fetchall()
        closed.update(r["rowid"] for r in more)
    return closed


def apply_quality_transitions_closure(conn: sqlite3.Connection, measurement_rowids: set[int]) -> set[int]:
    """`quality_transitions`（丸ごと）が参照する `measurements.measurement_id`
    を rowid に解決し、`measurement_rowids` に足す（参照の整合）。
    """
    ids = sorted({r["target_id"] for r in conn.execute(
        "SELECT DISTINCT target_id FROM quality_transitions WHERE target_table = 'measurements'"
    )})
    closed = set(measurement_rowids)
    chunk_size = 200
    for i in range(0, len(ids), chunk_size):
        chunk = ids[i : i + chunk_size]
        placeholder = ",".join("?" * len(chunk))
        rows = conn.execute(
            f'SELECT rowid FROM measurements WHERE measurement_id IN ({placeholder})', chunk
        ).fetchall()
        closed.update(r["rowid"] for r in rows)
    return closed


def select_wholesale_rowids(conn: sqlite3.Connection, table: str) -> list[int]:
    return [r[0] for r in conn.execute(f'SELECT rowid FROM "{table}" ORDER BY rowid')]


def select_cells_rowids(conn: sqlite3.Connection, doc_ids: list[str]) -> list[int]:
    placeholder = ",".join("?" * len(doc_ids))
    return [
        r[0]
        for r in conn.execute(
            f'SELECT rowid FROM cells WHERE doc_id IN ({placeholder}) ORDER BY rowid', doc_ids
        )
    ]


# ---------------------------------------------------------------------------
# declaration_counts.yaml（Issue #29 A-2）
# ---------------------------------------------------------------------------


def _year4(value: str | None) -> str | None:
    if not value or len(value) < 4 or not value[:4].isdigit():
        return None
    return value[:4]


def compute_leaf_cell_source_rows(rows: list[sqlite3.Row]) -> int:
    """b07 の「leaf セル」（grain='survey_period' で年をまたぐ区間）に集約される
    日付ありレコード数を数える。12形のうち区間形（'/' を含む4形）だけが対象——
    両端の年（先頭4桁）が違えば「年をまたぐ」。
    """
    n = 0
    for row in rows:
        observed_on = row["observed_on"]
        if not observed_on or "/" not in observed_on:
            continue
        left, right = observed_on.split("/", 1)
        y1, y2 = _year4(left), _year4(right)
        if y1 is not None and y2 is not None and y1 != y2:
            n += 1
    return n


def compute_occurrence_place_and_watershed_stats(rows: list[sqlite3.Row], geojson_path) -> dict:
    """`occurrence_place_declarations.yaml`（n_watershed_polygons 以外の2件）と
    `occurrence_watershed_v1_declarations.yaml`（3件）をサンプルに対して実測する。

    v1 のメモ化（0.001度バケット、`MIN(source_row_id)` を代表とする）を
    `scripts/migrate/point_in_polygon` の `locate()` で再現する。`source_row_id`
    はサンプルの rowid 相対順（= 材料化後の新しい rowid の相対順と一致する。
    モジュール docstring「決定論」参照）を使う。
    """
    polys = pip.load_polygons(geojson_path)
    grid = pip.build_grid(polys)

    geo_rows = [r for r in rows if r["lat"] is not None and r["lon"] is not None]
    exact_watershed: dict[str, str | None] = {}
    for row in geo_rows:
        matched, _near = pip.locate(row["lon"], row["lat"], polys, grid)
        exact_watershed[row["record_id"]] = matched[0] if len(matched) == 1 else None

    n_null = sum(1 for v in exact_watershed.values() if v is None)
    n_resolved = len(exact_watershed) - n_null

    # v1 母集団: period_raw(=observed_on) と lat/lon がどちらも非NULL
    v1_pop = [r for r in geo_rows if r["observed_on"] is not None]
    buckets: dict[tuple[str, str], list[sqlite3.Row]] = defaultdict(list)
    for row in v1_pop:
        key = (f"{row['lat']:.3f}", f"{row['lon']:.3f}")
        buckets[key].append(row)

    ws_to_ws = 0
    v1_assigned_exact_unassigned = 0
    v1_unassigned_exact_assigned = 0
    mixed_buckets = 0

    memo_year_agg: dict[tuple[str | None, str], dict[str, int]] = defaultdict(
        lambda: {"n": 0, "species_n": 0, "alien_n": 0, "redlist_n": 0, "_species": set()}
    )
    exact_year_agg: dict[tuple[str | None, str], dict[str, int]] = defaultdict(
        lambda: {"n": 0, "species_n": 0, "alien_n": 0, "redlist_n": 0, "_species": set()}
    )

    for members in buckets.values():
        # 代表 = rowid が最小（このサンプル内での相対順）
        rep = min(members, key=lambda r: r["rowid"])
        rep_watershed = exact_watershed.get(rep["record_id"])
        distinct_exact = {exact_watershed.get(m["record_id"]) for m in members}
        if len(distinct_exact) >= 2:
            mixed_buckets += 1
        for m in members:
            memo_ws = rep_watershed
            exact_ws = exact_watershed.get(m["record_id"])
            if memo_ws != exact_ws:
                if memo_ws is not None and exact_ws is not None:
                    ws_to_ws += 1
                elif memo_ws is not None and exact_ws is None:
                    v1_assigned_exact_unassigned += 1
                elif memo_ws is None and exact_ws is not None:
                    v1_unassigned_exact_assigned += 1
            year = _year4(m["observed_on"])
            if year is None:
                continue
            if memo_ws is not None:
                agg = memo_year_agg[(memo_ws, year)]
                agg["n"] += 1
                agg["_species"].add(m["scientific_name"])
                agg["alien_n"] += 1 if m["is_alien"] else 0
                agg["redlist_n"] += 1 if (m["red_list_category"] or "") != "" else 0
            if exact_ws is not None:
                agg = exact_year_agg[(exact_ws, year)]
                agg["n"] += 1
                agg["_species"].add(m["scientific_name"])
                agg["alien_n"] += 1 if m["is_alien"] else 0
                agg["redlist_n"] += 1 if (m["red_list_category"] or "") != "" else 0

    for agg in list(memo_year_agg.values()) + list(exact_year_agg.values()):
        agg["species_n"] = len(agg["_species"])
        del agg["_species"]

    keys_changed = 0
    for key in set(memo_year_agg) | set(exact_year_agg):
        a = memo_year_agg.get(key)
        b = exact_year_agg.get(key)
        if a is None or b is None:
            keys_changed += 1
            continue
        if any(a[f] != b[f] for f in ("n", "species_n", "alien_n", "redlist_n")):
            keys_changed += 1

    return {
        "place_id_null_count": n_null,
        "resolved_count": n_resolved,
        "memo_moved_records": {
            "ws_to_ws": ws_to_ws,
            "v1_assigned_exact_unassigned": v1_assigned_exact_unassigned,
            "v1_unassigned_exact_assigned": v1_unassigned_exact_assigned,
        },
        "memo_mixed_buckets": mixed_buckets,
        "org_watershed_year_keys_changed_vs_exact": keys_changed,
    }


def _create_rowid_temp_table(conn: sqlite3.Connection, name: str, rowids: set[int]) -> None:
    """`rowids`（大きな集合になりうる。バインドパラメータ100個/1000個の制限を
    避けるため、大きな `IN (...)` を作らずテンポラリテーブルに実体化する）を
    一時テーブル `name` に書く。
    """
    conn.execute(f"DROP TABLE IF EXISTS temp.{name}")
    conn.execute(f"CREATE TEMP TABLE {name} (rowid_value INTEGER PRIMARY KEY)")
    conn.executemany(f"INSERT INTO temp.{name} (rowid_value) VALUES (?)", [(r,) for r in rowids])


def build_declaration_counts(
    conn: sqlite3.Connection, ryuiki_selected: dict[str, set[int]], geojson_path=DEFAULT_GEOJSON,
) -> dict[str, int]:
    """`data/sample/declaration_counts.yaml` の中身（フラットな
    `"<宣言ファイル名>:<エントリ名>[.<内訳キー>]"` -> 整数）を実測する。
    """
    out: dict[str, int] = {}

    _temp_ready: set[str] = set()

    def _ensure_temp(table: str) -> str:
        """`table` 用の rowid 一時テーブルを（空でも）必ず作ってその名前を返す。
        `rowids` が空でも一時テーブル自体は作る——`count()` の早期リターンに
        頼ると、後段（`org_rows` の取得等）が無条件に参照する一時テーブルが
        1回も作られないまま残る事故になる（coverage.yaml が
        `organism_records` を一切選ばない構成でも安全に動くようにする）。
        """
        temp_name = f"__s01_{table}_rowids"
        if table not in _temp_ready:
            _create_rowid_temp_table(conn, temp_name, ryuiki_selected.get(table, set()))
            _temp_ready.add(table)
        return temp_name

    def count(table: str, where: str) -> int:
        temp_name = _ensure_temp(table)
        sql = (
            f'SELECT COUNT(*) FROM "{table}" t '
            f'JOIN temp.{temp_name} s ON t.rowid = s.rowid_value WHERE ({where})'
        )
        return conn.execute(sql).fetchone()[0]

    # organism_records の一覧は後段（occurrence_cube/place/watershed）でも
    # 使うため、ここで一時テーブルを確定させておく（0件でも作る。上の
    # `_ensure_temp` docstring 参照）。
    _ensure_temp("organism_records")

    # period_exceptions.yaml
    out["period_exceptions.yaml:atsugi_river_water_quality"] = count(
        "measurements", "source_id = 'atsugi_river_water_quality' AND length(measured_on) = 4"
    )

    # time_label_conventions.yaml（この2出典は全量が value_grain='hour' なので、
    # source_id 一致件数がそのまま該当件数になる。migrate/time_label_conventions.yaml 参照）
    out["time_label_conventions.yaml:sagamihara_taiki_hourly"] = count(
        "sensor_timeseries", "source_id = 'sagamihara_taiki_hourly'"
    )
    out["time_label_conventions.yaml:soramame_hourly_kanagawa"] = count(
        "sensor_timeseries", "source_id = 'soramame_hourly_kanagawa'"
    )

    # source_regions.yaml
    out["source_regions.yaml:gbif_kanagawa_occurrences"] = count(
        "organism_records", "source_id = 'gbif_kanagawa_occurrences'"
    )
    out["source_regions.yaml:inaturalist_kanagawa"] = count(
        "organism_records", "source_id = 'inaturalist_kanagawa'"
    )
    # 土地利用CSVは丸ごとコピーするので件数は原本と同じ（4,858）。
    out["source_regions.yaml:nlni_l03b_landuse_by_watershed"] = 4858

    # occurrence_period_shapes.yaml（12形。文字数で正確に対応する。coverage.yaml 参照）
    shape_lengths = {
        "year": 4, "month": 7, "year_interval": 9, "day": 10, "month_interval": 15,
        "instant_minute": 16, "instant_minute_z": 17, "instant_second": 19,
        "instant_second_z": 20, "day_interval": 21, "instant_millisecond_z": 24,
        "instant_minute_z_interval": 35,
    }
    for name, length in shape_lengths.items():
        out[f"occurrence_period_shapes.yaml:{name}"] = count(
            "organism_records", f"length(observed_on) = {length}"
        )

    # occurrence_cube_declarations.yaml
    org_rows = conn.execute(
        "SELECT t.rowid AS rowid, t.record_id, t.observed_on, t.lat, t.lon, t.scientific_name, "
        "t.is_alien, t.red_list_category "
        "FROM organism_records t JOIN temp.__s01_organism_records_rowids s ON t.rowid = s.rowid_value "
        "ORDER BY t.rowid"
    ).fetchall()
    out["occurrence_cube_declarations.yaml:leaf_cell_source_rows"] = compute_leaf_cell_source_rows(org_rows)

    # occurrence_place_declarations.yaml / occurrence_watershed_v1_declarations.yaml
    stats = compute_occurrence_place_and_watershed_stats(org_rows, geojson_path)
    out["occurrence_place_declarations.yaml:n_watershed_polygons"] = 377
    out["occurrence_place_declarations.yaml:place_id_null_count"] = stats["place_id_null_count"]
    out["occurrence_place_declarations.yaml:resolved_count"] = stats["resolved_count"]

    moved = stats["memo_moved_records"]
    total_moved = sum(moved.values())
    out["occurrence_watershed_v1_declarations.yaml:memo_moved_records"] = total_moved
    for key, value in moved.items():
        out[f"occurrence_watershed_v1_declarations.yaml:memo_moved_records.{key}"] = value
    out["occurrence_watershed_v1_declarations.yaml:memo_mixed_buckets"] = stats["memo_mixed_buckets"]
    out["occurrence_watershed_v1_declarations.yaml:org_watershed_year_keys_changed_vs_exact"] = stats[
        "org_watershed_year_keys_changed_vs_exact"
    ]

    return out


def _dump_declaration_counts_yaml(counts: dict[str, int]) -> str:
    lines = [
        "# scripts/s01_build_sample.py が生成した、縮小サンプルの件数の宣言の上書き値。",
        "# 手で編集しない（scripts/s01_build_sample.py を再実行して作り直すこと）。",
        "# 形式・使い方は docs/plans/PHASE_B_RECONCILIATION.md §5 と",
        "# scripts/migrate/period.py の apply_count_overlay/load_count_overlay_file を参照。",
        "",
    ]
    for key in sorted(counts):
        lines.append(f'"{key}": {int(counts[key])}')
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# derived_keys.yaml（Issue #29 A-3）
# ---------------------------------------------------------------------------


def build_derived_keys_yaml(baseline_json_path) -> str:
    baseline = json.loads(pathlib.Path(baseline_json_path).read_text(encoding="utf-8"))
    lines = [
        "# scripts/s01_build_sample.py が reports/derived_baseline.json（原本由来。正）から",
        "# 生成した、サンプル用の宣言的キー（Issue #29 A-3）。手で編集しない。",
        "#",
        "# サンプルでは行数が少なく、全量とは別の（より短い）列の組み合わせでも偶然一意に",
        "# なりうる。scripts/reconcile/common.derive_key の自動探索に任せず、全量ベース",
        "# ラインが実際に使ったキーをそのまま強制することで、サンプルの b01 が全量と",
        "# 違うキーで指紋を計算してしまう事故を防ぐ。",
        "",
    ]
    for table in sorted(baseline["tables"]):
        key = baseline["tables"][table]["key"]
        key_list = ", ".join(json.dumps(c, ensure_ascii=False) for c in key)
        lines.append(f"{table}:")
        lines.append(f"  key: [{key_list}]")
        lines.append(
            '  reason: "sample: 全量ベースライン（reports/derived_baseline.json）の自動導出キーを'
            'そのまま宣言化。サンプルでは行数が少ないため、探索A/Bに任せると別の短い組み合わせで'
            '偶然一意になりうる。"'
        )
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--ryuiki-db", default=str(DEFAULT_RYUIKI_DB))
    parser.add_argument("--cells-db", default=str(DEFAULT_CELLS_DB))
    parser.add_argument("--processed-dir", default=str(DEFAULT_PROCESSED_DIR))
    parser.add_argument("--coverage-yaml", default=str(DEFAULT_COVERAGE_YAML))
    parser.add_argument("--baseline-json", default=str(DEFAULT_BASELINE_JSON))
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    args = parser.parse_args()

    coverage = load_yaml(args.coverage_yaml)
    out_dir = pathlib.Path(args.out_dir)

    ryuiki_conn = _open_ro(args.ryuiki_db)
    cells_conn = _open_ro(args.cells_db)

    # --- 選択 ---
    selected = select_ryuiki_rowids(ryuiki_conn, coverage)
    selected["measurements"] = apply_measurement_site_variable_closure(
        ryuiki_conn, selected.get("measurements", set())
    )
    selected["measurements"] = apply_quality_transitions_closure(ryuiki_conn, selected["measurements"])
    for table in coverage.get("wholesale_ryuiki_tables", []):
        selected[table] = set(select_wholesale_rowids(ryuiki_conn, table))

    doc_ids = coverage["document_closure"]["doc_ids"]
    if len(doc_ids) < coverage["document_closure"]["min_documents"]:
        raise SystemExit("document_closure.doc_ids が min_documents に足りない")
    cells_selected: dict[str, list[int]] = {"cells": select_cells_rowids(cells_conn, doc_ids)}
    for table in coverage.get("wholesale_cells_tables", []):
        cells_selected[table] = select_wholesale_rowids(cells_conn, table)

    # --- テキストの書き出し ---
    ryuiki_tables = sorted(selected)
    _write_schema_sql(ryuiki_conn, ryuiki_tables, out_dir / "ryuiki_schema.sql")
    row_counts: dict[str, int] = {}
    for table in ryuiki_tables:
        rowids = sorted(selected[table])
        row_counts[table] = _write_table_sql(ryuiki_conn, table, rowids, out_dir / "ryuiki" / f"{table}.sql")

    cells_tables = sorted(cells_selected)
    _write_schema_sql(cells_conn, cells_tables, out_dir / "cells_schema.sql")
    for table in cells_tables:
        rowids = sorted(cells_selected[table])
        row_counts[f"cells.{table}"] = _write_table_sql(cells_conn, table, rowids, out_dir / "cells" / f"{table}.sql")

    processed_dir = pathlib.Path(args.processed_dir)
    processed_out = out_dir / "processed"
    processed_out.mkdir(parents=True, exist_ok=True)
    processed_hashes = {}
    for name in coverage.get("wholesale_processed_files", []):
        src = processed_dir / name
        dst = processed_out / name
        shutil.copyfile(src, dst)
        processed_hashes[name] = _sha256_file(src)

    # --- declaration_counts.yaml ---
    geojson_path = pathlib.Path(args.processed_dir) / "nlni_w12_watersheds.geojson"
    counts = build_declaration_counts(ryuiki_conn, selected, geojson_path)
    (out_dir / "declaration_counts.yaml").write_text(_dump_declaration_counts_yaml(counts), encoding="utf-8")

    # --- derived_keys.yaml ---
    (out_dir / "derived_keys.yaml").write_text(build_derived_keys_yaml(args.baseline_json), encoding="utf-8")

    # --- manifest.json ---
    manifest = {
        "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "generated_by": "scripts/s01_build_sample.py",
        "source_files": {
            "ryuiki.sqlite": _sha256_file(args.ryuiki_db),
            "cells.sqlite": _sha256_file(args.cells_db),
            **{f"processed/{name}": h for name, h in sorted(processed_hashes.items())},
        },
        "row_counts": dict(sorted(row_counts.items())),
    }
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False, sort_keys=False) + "\n", encoding="utf-8"
    )

    ryuiki_conn.close()
    cells_conn.close()

    print(f"→ {out_dir}")
    for table, n in sorted(row_counts.items()):
        print(f"  {table}: {n:,}行")
    return 0


if __name__ == "__main__":
    sys.exit(main())
