-- table: external_resource_format (7 rows, generated by scripts/s01_build_sample.py)
INSERT INTO "external_resource_format" ("dataset_key", "format_norm", "resource_key") VALUES
('ckan_bodik_kanagawa:001f9233-5589-43df-ab2e-704373b868d8', 'XLSX', 'ckan_bodik_kanagawa:c2e73ac7-cc51-4509-aeb1-9fe47dfcbe48'),
('ckan_kanagawa_pref:00595bdf-27ac-43fc-b69a-416a8be30941', 'PDF', 'ckan_kanagawa_pref:58bdd47b-c876-4eaf-b8f7-3df9b3ac3361'),
('ckan_sagamihara:22958a93-8403-41bc-8d05-099a8a70c02a', 'CSV', 'ckan_sagamihara:31d0c6d0-3d0d-4e2c-a3b5-ea57d094fc60'),
('ckan_yokohama:01542486-7522-498e-8315-f54ed19a8e58', 'CSV', 'ckan_yokohama:fa2979b4-1d66-4d6f-aac8-264670eb3dda'),
('estat_agri_census_kanagawa:000031511885', 'XLS', 'estat_agri_census_kanagawa:000031511885:file'),
('estat_census_population_kanagawa:000040454825', 'XLS', 'estat_census_population_kanagawa:000040454825:file'),
('estat_shozaiki_kanagawa:A002005212020', 'SHP', 'estat_shozaiki_kanagawa:A002005212020:file');
