-- table: mammal_mesh (1 rows, generated by scripts/s01_build_sample.py)
INSERT INTO "mammal_mesh" ("id", "mesh_code", "species", "species_ja", "survey_label", "survey_year", "confirmed", "lat", "lon", "source_id", "source_ref") VALUES
(300961, '52385722', 'tanuki', 'タヌキ', 'dai2kai', NULL, 0, 35.104167, 138.90625, 'biodic_mammal_mesh_kanagawa', 'https://arc-gis.biodic.go.jp/arcgis/rest/services/webgis/tanuki/FeatureServer/0 objectid=7621');
